ansible/ansibullbot

- MAINTAINERS-CORE.txt
- MAINTAINERS-EXTRAS.txt
nibalizer should always look at puppet. dguerri has moved on  to other
things.
> Update some owner lists

- MAINTAINERS-EXTRAS.txt
- prbot.py
Reverts ansible/ansibullbot#35. Looks like it's introduced some bugs, so gonna revert this for now and troubleshoot separately.
> Revert "github token and namespace support in PR bot"

- triage.py
~~~
PR #1629: ec2_vpc_subnet: fix edge case where boto returns empty list after subnet creation
Created at 2016-02-06 01:15:20
Updated at 2016-03-12 22:06:38
Debug: PR is mergeable
Debug: existing plugin modified, module maintainer should review
Debug: --- START Processing Comments:
Debug: erydo is module maintainer commented on 2016-03-12 22:06:38.
Debug: ...said shipit!
Debug: --- END Processing Comments
Debug: Thanks again to @caseylucas for this PR, and thanks @erydo for reviewing. Marking for inclusion.
Submitter: caseylucas
Maintainers: erydo
Current Labels: cloud, community_review
Actions: {'newlabel': ['shipit'], 'comments': [u'Thanks again to @caseylucas for this PR, and thanks @erydo for reviewing. Marking for inclusion.'], 'unlabel': []}
~~~
> triage: optimisations and fixes 

- triage.py
add needs_revision for build failures
/cc @gregdek
Implements #18
> triage: add label based on build status

- MAINTAINERS-EXTRAS.txt
> ritzk maintains cloud/vmware/vmware_vm_shell.py

- triage.py
/cc @gregdek 
Seems we have lowercase maintainer names and others with capital letters as well in our files.
> triage: make maintainer name case insensitive

- MAINTAINERS-CORE.txt
- MAINTAINERS-EXTRAS.txt
- templates/shipit_owner_pr.j2
Created the namespace when maintainer maintains 3 or more modules in the namespace. See each commit for better confirmability. 
Also adjusted the shipit owner template so other maintainers get informed.
/cc @gregdek
> maintainer namespaces

- triage.py
> triage: ignore pending_action

- triage.py
/cc @gregdek 
missed the case insensitive condition here
> triage: fix case in submitter name / maintainer name

- triage.py
/cc @gregdek 
otherwise this happens... c3353
> triage: fix backport must be evaluated after maintainers

- templates/work_in_progress.j2
- triage.py
closes #53 
NOTE: there is no label "work_in_progress" yet defined in the repos!
> triage: implement WIP

- templates/maintainer_unknown.j2
- triage.py
> triage: unknown maintainer inform some staff

- triage.py
the bot gets confused for PRs I did
> triage: make resmo human again

- MAINTAINERS-EXTRAS.txt
> add dj-wasabi as namespace maint for gitlab modules

- templates/needs_info.j2
- triage.py
> implement needs_info comment by maintainers

- triage.py
> fix do not remove new plugin label if labeled shipit

- triage.py
implements #75 (IMHO) looking at the issue type
/cc @gregdek
> implement labels by issue type

- templates/community_review_existing.j2
- templates/pending_action_close_me.j2
- triage.py
Implements #44 
/cc @gregdek 
Note: template text should be revisioned and a new label close_me must be added.
> implement close_me

- MAINTAINERS-CORE.txt
> fix unkonwn maintainers for junos

- triage.py
Reverts ansible/ansibullbot#87 because of #89
> Revert "implement labels by issue type"

- MAINTAINERS-CORE.txt
see PR core #3737
/cc @gregdek
> network/nxos/: privateip GGabriele

- MAINTAINERS-EXTRAS.txt
> windows/win_regmerge.ps1: jhawkesworth

- MAINTAINERS-EXTRAS.txt
> new modules, new maintainers

- MAINTAINERS-CORE.txt
Fixes #97 (97#issuecomment-224034769)
> Add 'ansible' to MAINTAINERS-CORE.txt for system/systemd.py

- MAINTAINERS-EXTRAS.txt
> new module, new maintainer

- triage.py
> add gce label for google modules

- templates/needs_revision_not_mergeable.j2
We occasionally see bad merges, since we have some existing documentation link to that to help the contributer
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ansible/ansibullbot/105)
> If rebase is needed link to existing instructions

- MAINTAINERS-EXTRAS.txt
$ cat database/influxdb/* | grep author
author: "Kamil Szczygiel (@kamsz)"
author: "Kamil Szczygiel (@kamsz)"
/cc @gregdek
> add influxdb maintainer

- MAINTAINERS-EXTRAS.txt
> new lxd modules, new maintainer

- MAINTAINERS-CORE.txt
Per https://github.com/ansible/ansible-modules-core/pull/4288
> Remove @rickmendes from elb_lb maintainer list

- templates/issue_closure.j2
- templates/issue_friendly_maintainer_reminder.j2
- templates/issue_invalid_module.j2
- templates/issue_missing_data.j2
- templates/issue_module_no_maintainer.j2
- templates/issue_needs_info.j2
- templates/issue_new.j2
- templates/issue_notify_maintainer.j2
- templates/issue_pending_closure.j2
- templates/issue_renotify_maintainer.j2
- templates/issue_wrong_repo.j2
Change the url from my previous branch to the main repo.
> Fix url to the help document

- MAINTAINERS-EXTRAS.txt
New module added by https://github.com/ansible/ansible-modules-extras/pull/2323/files
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ansible/ansibullbot/119)
> files/archive.py: bendoh

- MAINTAINERS-EXTRAS.txt
https://github.com/ansible/ansible-modules-extras/pull/1882/files
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ansible/ansibullbot/120)
> cloud/amazon/ec2_vpc_nat_gateway.py: linuxdynasty

- lib/triagers/defaulttriager.py
- triage.py
safe force intelligently decides that the module match is good enough that the actions can be forcefully applied, or pause for user input.
> safe_force option

- triage.py
/cc @jctanner @gregdek 
Test with PR https://github.com/ansible/ansible-modules-extras/pull/2704
> triage: implement bot_broken

- MAINTAINERS-EXTRAS.txt
authored few modules, which I would like to maintain and monitor for updates. I can also help with illumos/SmartOS subject matter expert if there is a desire.
> cloud/smartos and network/illumos maintainer

- MAINTAINERS-EXTRAS.txt
See https://github.com/ansible/ansible-modules-extras/pull/2803
> rocketchat: fix maintainer

- MAINTAINERS-CORE.txt
https://github.com/ansible/ansible-modules-core/pull/4218
> digital_ocean_tag.py -> kontrafiktion

- MAINTAINERS-EXTRAS.txt
Set maintainers for the following modules I've just merged:
https://github.com/ansible/ansible-modules-extras/pull/2001
https://github.com/ansible/ansible-modules-extras/pull/2394
https://github.com/ansible/ansible-modules-extras/pull/2396
https://github.com/ansible/ansible-modules-extras/pull/2788
https://github.com/ansible/ansible-modules-extras/pull/2202
https://github.com/ansible/ansible-modules-extras/pull/2148
https://github.com/ansible/ansible-modules-extras/pull/2416
> Owners for modules I've just merged

- MAINTAINERS-EXTRAS.txt
> add maintainer for jenkins_job

- lib/triagers/ansible_ansible_issuetriager.py
- lib/triagers/defaulttriager.py
- lib/triagers/issuetriager.py
- lib/utils/extractors.py
- lib/utils/moduletools.py
- lib/utils/version_tools.py
- lib/wrappers/defaultwrapper.py
- lib/wrappers/ghapiwrapper.py
- lib/wrappers/historywrapper.py
- tests/utils/issuetriager_mock.py
- triage.py
implements an issue triager for ansible/ansible and fixes many other bugs
> Ansible ansible issue triage

- MAINTAINERS-EXTRAS.txt
As discussed with @matze I'd also like to be maintainer of zypper_repository.
> Add robinro as maintainer of zypper_repository

- templates/shipit_by_ansible_member.j2
- triage.py
reported by @ryansb 
/cc @gregdek @gundalow @jctanner
> triage: comment correctly on shipit by an Ansible member

- MAINTAINERS-EXTRAS.txt
> update a couple maintainers

- templates/shipit_by_ansible_member.j2
follow up of f61c5579dc69df72e82b47af84d195b1d57b714a
/cc @gundalow
> fix maintainer not mentioned

- lib/triagers/defaulttriager.py
If no valid ansible version is in the description, check the comments.
> Check the comments for ansible version

- MAINTAINERS-EXTRAS.txt
@skornehl @bcoca @gundalow @abadger
> Add aditional set of eyes to extras/datadog_monitor

- lib/triagers/ansible_ansible_issuetriager.py
- lib/triagers/defaulttriager.py
- lib/triagers/issuetriager.py
The list of maintainers expansion was also expanding the list of authors inside the module, thereby permanently making the list expanded.
Found via https://github.com/ansible/ansible-modules-core/issues/5077#issuecomment-250182645
> Fix AMC 5077

- lib/triagers/ansible_ansible_issuetriager.py
- lib/triagers/defaulttriager.py
- lib/triagers/issuetriager.py
- lib/utils/extractors.py
- lib/wrappers/ghapiwrapper.py
Fixes https://github.com/ansible/ansibullbot/issues/129
> Resolve when merged

- MAINTAINERS-EXTRAS.txt
See https://github.com/ansible/ansible-modules-extras/pull/3137
/cc @gundalow
> add maintainer to statusio_maintenance

- MAINTAINERS-EXTRAS.txt
per https://github.com/ansible/ansible-modules-extras/pull/3202#issuecomment-254170876
> Add lekum as maintainer of taiga_issue

- lib/triagers/defaulttriager.py
- lib/triagers/issuetriager.py
- lib/utils/moduletools.py
The bot was spamming on https://github.com/ansible/ansible-modules-core/issues/5254
> Fix no maintainer for docker_network

- MAINTAINERS-CORE.txt
See https://groups.google.com/forum/#!msg/ansible-devel/G2QXbNjiWyA/g3cuvf2WAgAJ and https://github.com/ansible/ansible-modules-core/pull/5325#issuecomment-255087335
> Fix hostname maintainer

- MAINTAINERS-EXTRAS.txt
> missing maintainers

- MAINTAINERS-EXTRAS.txt
> add all missing maintainers

- MAINTAINERS-EXTRAS.txt
New extras modules.  Add the maintainer for them.
> Add proxysql maintainer

- MAINTAINERS-EXTRAS.txt
> new freeipa modules, new maintainer

- MAINTAINERS-EXTRAS.txt
Remove myself from the cloudstack maintainers list, I don't work with it any more unfortunately.
> Remove dazworrall from cloudstack

- MAINTAINERS-EXTRAS.txt
Created in https://github.com/ansible/ansible-modules-extras/pull/3292
> New module proxmox_kvm.py

- MAINTAINERS-CORE.txt
> Set group_by maintainer to ansible

- lib/utils/moduletools.py
> Slight refactor of special module handling and add include_vars

- MAINTAINERS-CORE.txt
> Notify ganeshnalawade about Junos changes

- MAINTAINERS-EXTRAS.txt
Also notify the Core Network team on any other network change
> network/a10 ->ericchou1

- MAINTAINERS-EXTRAS.txt
Perhaps not the best time for this PR, given module reorganisation, but want to add myself as maintainer of this module for future reference.
> Add jhawkesworth as maintainer of win_say

- MAINTAINERS-EXTRAS.txt
> remote_management/stacki/: bsanders bbyhuy

- MAINTAINERS-EXTRAS.txt
@GR360RY Is their anyone else I can list as a maintainer for these modules?
Maintainers will get notified when PRs or issues get raised, so it's good to have a few people listed
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ansible/ansibullbot/231)
> storage/infinidat/: GR360RY

- MAINTAINERS-EXTRAS.txt
Linked with https://github.com/ansible/ansible/pull/19602
> Add entry for network/omapi_host

- MAINTAINERS.txt
Sync after merging https://github.com/ansible/ansible/commit/7793424b1b8f705cd62e1f954953e926c572c7db
> sync smartos/ maintainers

- lib/utils/moduletools.py
https://github.com/ansible/ansible/issues/19755
> Fix mismatch on setup.ps1 for *nix setup related issues

- FILEMAP.json
https://github.com/ansible/ansible/pull/20166
> Update filemap for winrm/powershell/ps1 files

- lib/utils/extractors.py
- lib/utils/moduletools.py
https://github.com/ansible/ansible/issues/18179
> Ignore validate-modules when checking component for modules

- MAINTAINERS.txt
> Co-maintain timezone module

- MAINTAINERS.txt
> fix univention path, modules have been moved

- MAINTAINERS.txt
> cloudscale: new module, new maintainer

- lib/triagers/ansible.py
- missing_maintainers.py
- triage.py
and refactor triage classes to be usable outside triage functions
> Add the missing_maintainers script

- MAINTAINERS.txt
Add myself as a maintainer for this new module
> new module logstash_plugin

- lib/triagers/ansible.py
- lib/utils/webscraper.py
Fixes https://github.com/ansible/ansibullbot/issues/293
> needs_ci label for missing ci statuses

- MAINTAINERS.txt
#301 causes too many notifications for me (and others, apparently--see #313).
> Remove me as maintainer due to notification noise

- lib/triagers/ansible.py
Fixes https://github.com/ansible/ansibullbot/issues/312
> Implement ci_verified workflow

- MAINTAINERS.txt
https://github.com/ansible/ansible/issues/20942
> Remove h0nig from windows modules

- MAINTAINERS.txt
Linked with  https://github.com/ansible/ansible/pull/20971
> Add new vmware modules

- lib/triagers/ansible.py
> Deal with landscape.io in the ci statuses

- ISSUE_HELP.md
- lib/triagers/ansible.py
> re-add close_me command

- lib/triagers/ansible.py
Fixes https://github.com/ansible/ansibullbot/issues/331
> If no shippable status, don't do shipit

- MAINTAINERS.txt
```
[16:26] <@gundalow> dgarros: Could you please let me know the GitHub IDs of some other people that will look after these modules, they will get notified if issues & PRs get raised against your modules.
[16:26] < dgarros> @jeremyschulman
```
> network/aso/: dgarros jeremyschulman

- MAINTAINERS.txt
As requested by @ivanbojer in https://github.com/ansible/ansible/pull/20889#issuecomment-278472105
@ivanbojer FYI, feel free to raise a Pull Request to edit this list any anytime
> network/panos/: + jtschichold

- MAINTAINERS.txt
https://github.com/ansible/ansible/pull/19144
@jborean93 FYI
> New module win_find -> jborean93

- MAINTAINERS.txt
As discussed in ansible/ansible#21043.
CC: @gundalow
> Add maintainer for cloud/dimensiondata/dimensiondata_network.py

- MAINTAINERS.txt
In relation to a recent new module https://github.com/ansible/ansible/pull/19145
> new module win_reg_stat > jborean93

- MAINTAINERS.txt
> Remove erydo from MAINTAINERS.txt

- MAINTAINERS.txt
Related to https://github.com/ansible/ansible/pull/21099
> Add nsupdate maintainer

- MAINTAINERS.txt
As requested by Peter
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ansible/ansibullbot/355)
> network/ovs/: -> privateip

- COMPONENTMAP.json
- lib/triagers/ansible.py
- lib/triagers/defaulttriager.py
- lib/utils/extractors.py
- lib/utils/file_tools.py
- lib/wrappers/ghapiwrapper.py
- lib/wrappers/historywrapper.py
- scripts/find_missing_components.sh
- scripts/meta_component_dump.py
- tests/component/component_matching.py
- triage.py
component labels are only applied to:
1. pullrequests
2. untriaged issues
> Component labels from template "component name"

- lib/triagers/ansible.py
- lib/utils/moduletools.py
https://github.com/ansible/ansible/pull/20113
> Fix shipit on #20113

- MAINTAINERS.txt
https://github.com/ansible/ansible/pull/21247/files
> New module: mattermost.py: bjolivot

- MAINTAINERS.txt
As requested in 
https://github.com/ansible/ansible/pull/20436#issuecomment-279919765
> network/ordnance/: djh00t alexanderturner

- MAINTAINERS.txt
As requested by wwitzel3 on Slack
> ansible_tower -> ghjm jlaska matburt wwitzel3

- lib/triagers/ansible.py
- lib/triagers/plugins/needs_revision.py
- templates/commit_msg_mentions.j2
> Sets needs_revision and notify submitter if commit msg mentions someone.

- MAINTAINERS.txt
Maintainer info for win_region module just merged in.
> Added maintainer for win_region

- MAINTAINERS.txt
> Add s-hertel as Elasticache Snapshot maintainer

- MAINTAINERS.txt
> Add maintainer of pubnub_blocks as namespace maint

- MAINTAINERS.txt
As discussed in https://github.com/ansible/ansible/pull/19698 looking to get myself added as a maintainer for Linode module.
> Add maintainer for cloud/linode/linode.py

- MAINTAINERS.txt
Noticed these were missing in the list.
> Adding 3 missing windows modules

- lib/triagers/ansible.py
- lib/triagers/plugins/backports.py
Fixes https://github.com/ansible/ansibullbot/issues/367
> Add backport label to appropriate PRs

- MAINTAINERS.txt
> Add new maintainer to win_chocolatey due to unresponsiveness

- lib/wrappers/defaultwrapper.py
> Wrap the calls for commit parents and messages to avoid ssl timeouts.

- MAINTAINERS.txt
Ansible use a dedicated directory for this modules
> Update the mongodb modules path

- MAINTAINERS.txt
The creator of all the modules
> network/lenovo -> dkasberg

- MAINTAINERS.txt
Questions:
* Who for `asa`
* Who for `netvisor`
* Who for `sros`
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ansible/ansibullbot/386)
> [WIP] Network maintainers DO NOT MERGE

- MAINTAINERS.txt
> Remove a few previous maintainers

- lib/utils/shippable_api.py
- templates/shippable_test_result.j2
> Fix traceback on jsonify

- lib/triagers/ansible.py
> Skip test result comments that exceed max message size.

- lib/constants.py
- lib/triagers/ansible.py
- scripts/list_open_issues_with_needs_info.sh
- templates/needs_info_base.j2
> Re-implement needs_info timeouts.

- MAINTAINERS.txt
Changed my Github handle from `ganeshnalawade` to `ganeshrn`
> Change github handle

- MAINTAINERS.txt
As discussed: https://github.com/ansible/ansible/pull/22555#issuecomment-288157528
> Add new maintainer for win_firewall_rule

- lib/decorators/github.py
- lib/triagers/ansible.py
- lib/triagers/defaulttriager.py
- lib/triagers/plugins/needs_revision.py
- lib/utils/shippable_api.py
- lib/utils/timetools.py
- lib/utils/webscraper.py
- lib/wrappers/defaultwrapper.py
- lib/wrappers/historywrapper.py
- scripts/check_ci_verified_actions.py
- scripts/list_open_prs_with_ci_verified.sh
- scripts/list_open_prs_with_status.sh
- triage.py
> Add/Remove the ci_verified label based on test properties.

- MAINTAINERS.txt
I will be refactoring and adding tests for various nxos modules,
thus adding myself as maintainer.
> Add rcarrillocruz as nxos maintainer

- MAINTAINERS.txt
Signed up for 2.4 code clean up and unit tests writing, thus adding
myself as maintainer.
> Add rcarrillocruz as ovs maintainer

- MAINTAINERS.txt
poor postgresql user :(
related to https://github.com/ansible/ansible/pull/22613
> Adopt orphan postgresql_user

- MAINTAINERS.txt
Fixes https://github.com/ansible/ansibullbot/issues/464
> Remove fanckcuny as that is not a valid username

- MAINTAINERS.txt
As discussed in todays core meeting I'd like to become maintainer of the git module.
cc @abadger
> Make me (@robinro) maintainer of the git module

- lib/triagers/ansible.py
- lib/triagers/plugins/needs_revision.py
- lib/utils/moduletools.py
- lib/utils/webscraper.py
- lib/wrappers/defaultwrapper.py
- scripts/list_open_prs_with_needs_rebase.sh
- templates/no_shippable_yaml.j2
Fixes https://github.com/ansible/ansibullbot/issues/406
> Missing shippable yaml

- MAINTAINERS.txt
> network/nxos + rahushen

- MAINTAINERS.txt
https://github.com/ansible/ansible/pull/19461
> system/gconftool2.py: kevensen

- lib/utils/webscraper.py
> Lowercase the state div for comparision in lambda expression.

- lib/triagers/plugins/needs_revision.py
> Unset ci_verified if added by human and no longer valid.

- MAINTAINERS.txt
> Add akasurde as gconftool-2 maintainer

- MAINTAINERS.txt
> Updated dellos* maintainers

- lib/triagers/ansible.py
> Disable auto-assignment.

- MAINTAINERS.txt
Follow on from https://github.com/ansible/ansible/pull/24024
> Split network & net_tools & sort file

- lib/triagers/plugins/needs_revision.py
- lib/utils/shippable_api.py
Fixes https://github.com/ansible/ansibullbot/issues/513
> Fix shippable queries for new status url jobid format

- lib/utils/webscraper.py
> Ignore missing elements in reviews.

- MAINTAINERS.txt
> Add akasurde as github_issue maintainer

- lib/utils/webscraper.py
> Look for altertive div classes on the created-at block of html

- lib/utils/webscraper.py
> Fix exception in webscraper for PR reviews.

- MAINTAINERS.txt
re: https://github.com/ansible/ansibullbot/pull/508
> Remove rmorlok

- MAINTAINERS.txt
> Add new maintainer for postgresql_* modules.

- MAINTAINERS.txt
> Add akasurde as maintainer of sysctl

- MAINTAINERS.txt
added myself as maintainer for win_firewall
> win_firewall maintainer

- examples/ansibullbot.cfg
- lib/constants.py
- lib/triagers/ansible.py
- lib/utils/receiver_client.py
- lib/utils/webscraper.py
- services/receiver/ansibot_receiver.py
This is a service and client code that allows ansibot (for the ansible triage code) to send the scraped issue summaries and processed metadata to a datastore. The service is a simple flask app that puts the data into mongodb.
> ansibullbot metadata and issue summary receiver

- MAINTAINERS.txt
Unmaintained modules @jborean93 was willing to take on.
Also add the new win_dsc module.
> Various changes to Windows maintainership

- MAINTAINERS.txt
> Add maintainer for ALB modules

- lib/constants.py
- lib/decorators/github.py
- lib/triagers/ansible.py
- lib/triagers/defaulttriager.py
- lib/utils/descriptionfixer.py
- lib/utils/extractors.py
- lib/utils/shippable_api.py
- lib/utils/version_tools.py
- lib/utils/webscraper.py
- lib/wrappers/defaultwrapper.py
- lib/wrappers/ghapiwrapper.py
- lib/wrappers/historywrapper.py
Fixes https://github.com/ansible/ansibullbot/issues/570
> Add new config option to avoid breakpoints in prod

- MAINTAINERS.txt
> Add Ted as dynamodb_ttl maintainer

- lib/decorators/github.py
- lib/triagers/ansible.py
- lib/utils/gh_gql_client.py
The webscraper code is "functional" but it's also not easy to maintain and keep up with. This PR introduces a graphql client that can do much of the same work via github's new graphql api.
> Graph api client

- MAINTAINERS.txt
> Add Flavio as helm module maintainer

- MAINTAINERS.txt
> Add akasurde as vmware_vswitch maintainer

- lib/triagers/ansible.py
- lib/utils/moduletools.py
Fixes https://github.com/ansible/ansibullbot/issues/589
> Missing maintainer label

- lib/decorators/github.py
- lib/wrappers/defaultwrapper.py
> Wrap the get_template_data function with the ratelimited wrapper.

- lib/triagers/ansible.py
> slight refactor on collect_repos to get better rate limit handling

- lib/decorators/github.py
> Catch the httlib.IncompleteRead exception

- lib/decorators/github.py
Fixes https://github.com/ansible/ansibullbot/issues/585
> Check the json data before declaring rate limit check was successful

- lib/triagers/ansible.py
- lib/triagers/plugins/backports.py
Fixes https://github.com/ansible/ansibullbot/issues/568
> Backport label

- lib/triagers/ansible.py
- lib/utils/moduletools.py
Fixes https://github.com/ansible/ansibullbot/issues/572
> Set the namespace maintainers on new modules

- lib/decorators/github.py
Fixes https://github.com/ansible/ansibullbot/issues/602
> Handle BadStatusLine better

- lib/utils/webscraper.py
> Check if the scraped page includes message about taking too long to load

- lib/triagers/plugins/needs_revision.py
- lib/utils/gh_gql_client.py
- lib/utils/shippable_api.py
Fixes https://github.com/ansible/ansibullbot/issues/421
> Do not leave empty test result comments.

- FILEMAP.json
> Add tag vmware, cloud for vcenter

- lib/triagers/ansible.py
> add support:xxxx labels

- lib/utils/iterators.py
- lib/wrappers/ghapiwrapper.py
> delete ondisk cache if it fails to load

- README.md
- ansibullbot/constants.py
- ansibullbot/parsers/botmetadata.py
- ansibullbot/triagers/ansible.py
- ansibullbot/utils/file_tools.py
- ansibullbot/utils/moduletools.py
- ansibullbot/utils/receiver_client.py
- requirements.txt
- scripts/ansibot_status.cgi
- scripts/cleanup_cache.sh
- scripts/maintainer_v1-v2.py
- test/unit/parsers/metadata_1.yml
- test/unit/parsers/test_bot_metadata_parser.py
related to https://github.com/ansible/ansibullbot/pull/627
> new bot metadata parser for maintainers v2

- templates/merge_commit_notify.j2
> Minor typo in commit template

- ansibullbot/triagers/ansible.py
> Ignore component labels if there are merge commits.

- ansibullbot/triagers/ansible.py
Fixes https://github.com/ansible/ansibullbot/issues/648
> Fix pathing error on new module detection

- ansibullbot/constants.py
Fixes https://github.com/ansible/ansibullbot/issues/651
> Fix config parser casting all data to string

- ansibullbot/utils/receiver_client.py
> Convert URL value to string

- ansibullbot/utils/moduletools.py
> Return empty list if module file is not found.

- ansibullbot/triagers/ansible.py
- ansibullbot/utils/gh_gql_client.py
This pull-request allows to fetch only pull-requests specified with `pr` switch.
> Fetch only specified pull-requests when 'pr' switch used

- ansibullbot/triagers/plugins/shipit.py
Lines removed from `test/sanity/*/*.txt` files are checked by the CI, hence such pull-requests can be safely automerged.
> Allow automerge when test/sanity/*/*.txt updated with deletions

- ISSUE_HELP.md
The purpose of this pull request is to add information about existing labels and improve formatting.
> Add a 'labels' section, update TOC, use links for commands and labels, add icon

- ansibullbot/triagers/plugins/ci_rebuild.py
> Get the runid from the description if the targeturl is not an integer

- ISSUE_HELP.md
- add missing labels
- some labels were referring to working groups instead of namespaces
> Documentation: add missing labels, fix categorization

- ISSUE_HELP.md
section is copied from PR-FLOW.md in community repository.
Closes #382.
Related: https://github.com/ansible/community/issues/169
> Add an overview section

- scripts/slack-notice.py
Plan to use this to send notices when SystemD restarts the bot.
> Add script to post notice to Slack

- ansibullbot/utils/extractors.py
- tests/unit/utils/test_template_extractor.py
> Replace modules with spaces

- ansibullbot/triagers/ansible.py
> Do not close the  migrated issue if it was not in the ansible-modules repos

- ansibullbot/triagers/ansible.py
- ansibullbot/triagers/defaulttriager.py
- ansibullbot/triagers/plugins/shipit.py
> Refactoring and a fix for mapping curated to certified.

- ansibullbot/triagers/plugins/shipit.py
Fixes https://github.com/ansible/ansibullbot/issues/716
> Missing import in shipit.py

- ISSUE_HELP.md
Linking here from the community doc and just wanted to keep the name consistent.
> Change ansibot to ansibullbot in ISSUE_HELP.md

- ISSUE_HELP.md
Add documentation for rebuild_merge command
> Add documentation for rebuild_merge command

- ISSUE_HELP.md
> Minor typo correction

- ansibullbot/triagers/ansible.py
Handle `--repo` switch, remove duplicated code.
> take in account '--repo' switch and remove duplicated code

- triage_simple.py
> Fix import for simpletriage

- ansibullbot/triagers/ansible.py
- ansibullbot/triagers/defaulttriager.py
There isn't any switch/parameter starting with `gh_`.
> Remove gh_* attributes, keep github_* ones

- ansibullbot/triagers/defaulttriager.py
```
2017-09-10 15:11:16,972 ERROR Uncaught exception
File "/home/ansibot/ansibullbot/triage_ansible.py", line 137, in <module>
main()
File "/home/ansibot/ansibullbot/triage_ansible.py", line 133, in main
AnsibleTriage(args).start()
File "/home/ansibot/ansibullbot/ansibullbot/triagers/defaulttriager.py", line 218, in start
self.loop()
File "/home/ansibot/ansibullbot/ansibullbot/triagers/defaulttriager.py", line 347, in loop
self.run()
File "/home/ansibot/ansibullbot/ansibullbot/triagers/ansible.py", line 528, in run
action_meta = self.apply_actions(iw, actions)
File "/home/ansibot/ansibullbot/ansibullbot/triagers/defaulttriager.py", line 417, in apply_actions
self.execute_actions(iw, actions)
File …
```
> Actions class is not iterable

- ansibullbot/wrappers/defaultwrapper.py
> Remove breakpoint

- ansibullbot/triagers/ansible.py
> Fix save_meta parameters

- ansibullbot/triagers/ansible.py
- ansibullbot/triagers/plugins/contributors.py
- ansibullbot/utils/file_tools.py
- ansibullbot/utils/moduletools.py
> Set the new_contributor label

- tests/unit/utils/test_githubid_extractor.py
> Add another testcase for #704

- ansibullbot/utils/moduletools.py
> modules directory could contain doc files

- ansibullbot/triagers/plugins/shipit.py
- templates/community_shipit_notify.j2
> Don't notify submitter

- ansibullbot/utils/shippable_api.py
- ansibullbot/wrappers/historywrapper.py
Shippable api: improve HTTP requests
- add a timeout
- fix URL which were sometimes wrong
- avoid to repeat the same HTTP query
- use tenacity (avoid potential infinite loop)
> Shippable api: improve HTTP requests

- .pylintrc
- ansibullbot/triagers/ansible.py
- ansibullbot/triagers/defaulttriager.py
- ansibullbot/triagers/simpletriager.py
- ansibullbot/utils/gh_gql_client.py
- ansibullbot/utils/systemtools.py
- ansibullbot/utils/version_tools.py
- ansibullbot/wrappers/defaultwrapper.py
- pylint_plugins/triagers.py
- triage_ansible.py
- triage_simple.py
- Add Pylint plugins for triagers (due to dynamic attributes)
- move common triagers code to `defaulttriager.py`
- remove useless `self.args`
The next step will be:
- remove code which handles old repositories (`ansible-modules-core` and `ansible-modules-extras`)
> Attributes initialization v2

- ansibullbot/triagers/plugins/needs_revision.py
- tests/unit/triagers/plugins/test_needs_revision.py
See https://github.com/ansible/ansibullbot/issues/712#issuecomment-322975356.
Related: #739 
Fix #712
> ready_for_review overrides outdated reviews

- ansibullbot/triagers/plugins/needs_revision.py
> Do not set ready_for_review to a bool val.

- ansibullbot/utils/component_tools.py
> Get only exact matches when looking for a module for a test target.

- ansibullbot/triagers/plugins/component_matching.py
- ansibullbot/utils/component_tools.py
Fixes https://github.com/ansible/ansibullbot/issues/830
Fixes https://github.com/ansible/ansibullbot/issues/829
> Fix a few recent issues

- ansibullbot/triagers/ansible.py
- ansibullbot/triagers/plugins/component_matching.py
Fixes https://github.com/ansible/ansibullbot/issues/837
Refixes https://github.com/ansible/ansibullbot/issues/787
> Enhance bad_pr detection slightly and bypass most action creation if true

- ansibullbot/utils/component_tools.py
Fixes https://github.com/ansible/ansibullbot/issues/840
> Walk up the meta tree to find additional people to ignore

- ISSUE_HELP.md
- ansibullbot/triagers/ansible.py
- ansibullbot/triagers/plugins/label_commands.py
Waffling exceptions are thrown if a label toggles 20 times or more.
https://github.com/ansible/ansibullbot/blob/master/ansibullbot/wrappers/historywrapper.py#L752
Related https://github.com/samdoran/ansible-role-ansibullbot/pull/4
> Waffling override cmd

- ansibullbot/decorators/github.py
- ansibullbot/triagers/ansible.py
Fixes https://github.com/ansible/ansibullbot/issues/845
> Handle migrations from private repos

- ansibullbot/triagers/plugins/contributors.py
> Fix adding new_contributor label

- ansibullbot/triagers/ansible.py
- ansibullbot/triagers/plugins/backports.py
> Backports influence the affects_x.x label

- ansibullbot/triagers/plugins/needs_info.py
https://github.com/ansible/ansible/issues/32432
> Fix needs_info auto-{warn,close}

- ansibullbot/wrappers/defaultwrapper.py
> RateLimit repo_full_name

- ansibullbot/utils/component_tools.py
fixes https://github.com/ansible/ansibullbot/issues/865
> Walk the last segment of the path for meta

- ansibullbot/triagers/defaulttriager.py
> Use WatchedFileHandler for log file

- ansibullbot/triagers/ansible.py
Addition to https://github.com/ansible/ansibullbot/pull/872
> Simplify issue type labels

- ansibullbot/triagers/plugins/performance.py
```
2018-03-03 01:33:33,898 ERROR Uncaught exception
main()
self.loop()
self.run()
File "/home/ansibot/ansibullbot/ansibullbot/triagers/ansible.py", line 437, in run
File "/home/ansibot/ansibullbot/ansibullbot/triagers/ansible.py", line 1747, in process
self.meta.update(get_performance_facts(iw, self.meta))
File "/home/ansibot/ansibullbot/ansibullbot/triagers/plugins/performance.py", line 10, in …
```
> Handle null bodies and titles

- ISSUE_HELP.md
> ISSUE_HELP.md: update labels

- scripts/list_bug_report.sh
- scripts/list_bugfix_pull_request.sh
- scripts/list_docs_pull_request.sh
- scripts/list_docs_report.sh
- scripts/list_feature_idea.sh
- scripts/list_feature_pull_request.sh
- scripts/replace_labels.py
Adding a weird script as an addition to https://github.com/ansible/ansibullbot/pull/872, for a review before running it. Could be re-worked for similar purpose in future.
Tested on:
https://github.com/ansible/ansible/issues/12445 (apparently I suck at `requests` hence the several tries to do it right)
> Add script for replacing labels

- ansibullbot/wrappers/historywrapper.py
> Some reviews are missing commit ids

- ansibullbot/triagers/plugins/component_matching.py
- scripts/generate_issues_by_file.py
Fixes https://github.com/ansible/ansibullbot/issues/885
> misc changes

- scripts/maintainer_v1-v2.py
i don't use VMWare enough since some months to maintain this
> Remove myself from VMWare

- ansibullbot/triagers/plugins/shipit.py
> Gate automerge if CI is still running or not success.

- ansibullbot/triagers/ansible.py
- ansibullbot/triagers/plugins/component_matching.py
> Add labels for new plugins

- ansibullbot/wrappers/defaultwrapper.py
> Reviews don't need to be fetched until necessary

- ansibullbot/triagers/ansible.py
- ansibullbot/triagers/plugins/component_matching.py
> If the PR is empty and not WIP, close it

- ansibullbot/triagers/ansible.py
Fixes https://github.com/ansible/ansibullbot/issues/911
> Allow affects_* on non-backport PRs

- ansibullbot/triagers/ansible.py
- ansibullbot/wrappers/ghapiwrapper.py
Fixes https://github.com/ansible/ansibullbot/issues/535
> Apply valid component labels

- ansibullbot/utils/version_tools.py
`VERSION` file no longer available - https://github.com/ansible/ansible/pull/40421
> Retrieving devel version changed

- ansibullbot/utils/version_tools.py
This reverts commit 904ab82dbb68a9f882c4a3e172e6becd53f96e7f.
> Revert "Retrieving devel version changed (#921)"

- ansibullbot/triagers/ansible.py
- ansibullbot/triagers/plugins/ci_rebuild.py
- ansibullbot/utils/shippable_api.py
- tests/unit/triagers/plugins/test_rebuild_merge.py
Fixes https://github.com/ansible/ansibullbot/issues/920
Tested on https://github.com/ansible/ansible/pull/26299
> Cancel CI run on merge_commit/bad_pr

- ansibullbot/triagers/ansible.py
- ansibullbot/triagers/plugins/traceback.py
Fixes https://github.com/ansible/ansibullbot/issues/551
Tested on:
https://github.com/ansible/ansible/issues/40220
https://github.com/ansible/ansible/issues/40453
https://github.com/ansible/ansible/issues/40515
> Add traceback label

- ansibullbot/triagers/ansible.py
- ansibullbot/triagers/plugins/needs_revision.py
- tests/unit/triagers/plugins/test_shipit.py
- tests/utils/issue_mock.py
> Filter out and map partial shippable runs to their full runs

- ansibullbot/triagers/plugins/ci_rebuild.py
Fixes https://github.com/ansible/ansibullbot/issues/934
> Ignore other CI's other than shipabull's

- .gitmodules
- ansible.cfg
- playbooks/group_vars/all.yml
- playbooks/hosts
- playbooks/hosts.yml
- playbooks/setup-ansibullbot.yml
- playbooks/tower.yml
Change inventory to YAML style
Install and configure `yum-cron` to keep systems up to date
> Add yum-cron role

- ansibullbot/triagers/ansible.py
- ansibullbot/triagers/plugins/needs_revision.py
- ansibullbot/utils/shippable_api.py
Fixes https://github.com/ansible/ansibullbot/issues/941
> Merge commit only cancel

- templates/merge_commit_notify.j2
> Correct link to developing_rebasing.html

- ansibullbot/triagers/plugins/shipit.py
> Code clean up as per review

- ansibullbot/parsers/botmetadata.py
- ansibullbot/triagers/ansible.py
- ansibullbot/triagers/defaulttriager.py
- ansibullbot/triagers/plugins/needs_info.py
- ansibullbot/triagers/plugins/needs_revision.py
- ansibullbot/utils/descriptionfixer.py
- ansibullbot/utils/extractors.py
- ansibullbot/utils/file_tools.py
- ansibullbot/utils/moduletools.py
- ansibullbot/utils/shippable_api.py
- ansibullbot/utils/timetools.py
- ansibullbot/utils/webscraper.py
So we can https://github.com/samdoran/ansible-role-ansibullbot/pull/6
> epdb calls cleanup

- ansibullbot/parsers/botmetadata.py
- ansibullbot/triagers/ansible.py
- ansibullbot/triagers/plugins/backports.py
- ansibullbot/triagers/plugins/ci_rebuild.py
- ansibullbot/triagers/plugins/component_matching.py
- ansibullbot/triagers/plugins/performance.py
- ansibullbot/triagers/plugins/py3.py
- ansibullbot/triagers/simpletriager.py
- ansibullbot/utils/component_tools.py
- ansibullbot/utils/descriptionfixer.py
- ansibullbot/utils/extractors.py
- ansibullbot/utils/file_tools.py
- ansibullbot/utils/gh_gql_client.py
- ansibullbot/utils/migrator.py
- ansibullbot/utils/moduletools.py
- ansibullbot/utils/receiver_client.py
- ansibullbot/utils/shippable_api.py
- ansibullbot/utils/systemtools.py
- ansibullbot/utils/timetools.py
- ansibullbot/utils/version_tools.py
- ansibullbot/utils/webscraper.py
- ansibullbot/wrappers/defaultwrapper.py
- ansibullbot/wrappers/historywrapper.py
- ansibullbot/wrappers/pullrequestwrapper.py
* Redundant state key
* Simplify comparison
* Simplify sleep assignment
* PEP8 fixes
> Miscellaneous changes

- ansibullbot/utils/shippable_api.py
> Compress shippable data when storing on disk.

- ansibullbot/triagers/plugins/small_patch.py
Fixes https://github.com/ansible/ansibullbot/issues/965
> Fix KeyError on small_patch

- ansibullbot/parsers/botmetadata.py
- ansibullbot/triagers/plugins/needs_revision.py
- ansibullbot/utils/file_tools.py
- ansibullbot/utils/moduletools.py
Fixes https://github.com/ansible/ansibullbot/issues/968
> Add missing constants imports

- ansibullbot/triagers/ansible.py
- ansibullbot/triagers/plugins/community_workgroups.py
- templates/community_workgroups.j2
> On a new issue/PR, inform the submitter about relevant working groups.

- ansibullbot/triagers/ansible.py
- ansibullbot/triagers/plugins/needs_revision.py
- ansibullbot/utils/shippable_api.py
Addresses https://github.com/ansible/ansibullbot/issues/982
> Use a better URL for shippable run queries

- templates/community_workgroups.j2
> Added Github username to address user

- ansibullbot/wrappers/defaultwrapper.py
Related to https://github.com/ansible/ansibullbot/issues/959
> Log info when TypeError on sd['target_url']

- ansibullbot/triagers/plugins/needs_revision.py
- tests/fixtures/needs_revision/1_issue.yml
- tests/fixtures/needs_revision/1_reviews.json
- tests/fixtures/needs_revision/2_issue.yml
- tests/unit/triagers/plugins/test_needs_revision.py
Fixes https://github.com/ansible/ansibullbot/issues/994
> Remove needs_revision if shipit from the same user

- ansibullbot/wrappers/defaultwrapper.py
https://github.com/ansible/ansibullbot/issues/1004
> Log response on 'merge failed'

- ansibullbot/triagers/plugins/needs_revision.py
Fixes https://github.com/ansible/ansibullbot/issues/895
> Use Shippable ci_status when getting last_run

- ansibullbot/triagers/ansible.py
- ansibullbot/utils/shippable_api.py
- ansibullbot/wrappers/defaultwrapper.py
- templates/fork.j2
Fixes https://github.com/ansible/ansibullbot/issues/971
> Auto-close PRs not using forks

- ansibullbot/parsers/botmetadata.py
- tests/unit/parsers/test_bot_metadata_parser.py
Propagate `labels`, `support` and `supported_by` keys:
* `labels`: entry inherits from all ancestors
* `support`/`supported_by`: value isn't cumulated, entry inherits from the nearest ancestor and only if the entry doesn't set this keyword
cc @gundalow 
Unit tests provided.
> BOTMETA: propagate 'labels', 'support' and 'supported_by' key

- ansibullbot/constants.py
- ansibullbot/decorators/github.py
- ansibullbot/triagers/defaulttriager.py
- ansibullbot/wrappers/defaultwrapper.py
- scripts/github_sim.py
* config to set the github url to allow for testing mocked endpoints
* github_sim flask script to simulate a minimal part of the github rest api
* sleep 2 minutes if 500 ISE is encountered
Fixes https://github.com/ansible/ansibullbot/issues/1025
> Handle 500 ISEs from github's API.

- ansibullbot/triagers/plugins/component_matching.py
- tests/unit/triagers/plugins/test_shipit.py
> Remove unused get_component_match_facts params

- ansibullbot/utils/component_tools.py
- ansibullbot/utils/file_tools.py
- tests/unit/utils/test_component_tools.py
Fixes https://github.com/ansible/ansibullbot/issues/688
> Allow for wildcard matching in BOTMETA.yml

- ansibullbot/triagers/ansible.py
- ansibullbot/triagers/plugins/component_matching.py
- templates/bad_pr.j2
> Explain the reason of bad PR in a comment

- ansibullbot/triagers/ansible.py
- ansibullbot/utils/component_tools.py
- ansibullbot/utils/moduletools.py
Fixes https://github.com/ansible/ansibullbot/issues/1042
Fixes https://github.com/ansible/ansibullbot/issues/1053
> Pull module meta when collecting meta for a file

- scripts/ansibot_status.cgi
Fixes https://github.com/ansible/ansibullbot/issues/972
> Fix internal server error in status.cgi

- ansibullbot/wrappers/defaultwrapper.py
https://github.com/ansible/ansibullbot/issues/1068
> Add better logging around the 'KeyError: 0' issue

- ansibullbot/triagers/plugins/small_patch.py
- ansibullbot/wrappers/defaultwrapper.py
https://github.com/ansible/ansibullbot/issues/1071
> RateLimit getting files from commit

- shippable.yml
- test-requirements.txt
I'm concerned that test coverage isn't that good. Lets see if we can generate some metrics to prove this either way.
> Codecov.io support

- ansibullbot/wrappers/defaultwrapper.py
Fixes https://github.com/ansible/ansibullbot/issues/1068
> Fix rate limit in get_reviews

- ansibullbot/wrappers/defaultwrapper.py
> Add more logging for debugging of get_reviews

- ansibullbot/utils/component_tools.py
- tests/unit/utils/test_component_tools.py
Fixes ansible/ansibullbot#1049
cc @jctanner @gundalow
> Copy authors and maintainers info from module

- ansibullbot/utils/component_tools.py
- ansibullbot/utils/extractors.py
- tests/unit/utils/test_component_tools.py
> revamp support level enumeration in component matcher

- ansibullbot/utils/moduletools.py
- tests/unit/utils/test_githubid_extractor.py
> Return an empty list if None is passed in for the author

- ansibullbot/decorators/github.py
Fixes sentry issue ...
https://sentry.io/red-hat-ansibullbot/ansibullbot/issues/804854465
> Sleep 2 minutes if github returns a 502

- ansibullbot/utils/shippable_api.py
Addresses https://github.com/ansible/ansibullbot/issues/1123
> Add more log entries for shippable rebuild requests

- ansibullbot/triagers/ansible.py
- ansibullbot/wrappers/defaultwrapper.py
- templates/incoming_ref_missing.j2
> Close missing incoming branch with advice

- ansibullbot/triagers/plugins/shipit.py
- tests/unit/triagers/plugins/test_shipit.py
rebuild_merge wasn't forcing automerge shipit tests to pass
> Fix rebuild_merge for core folks

- ansibullbot/triagers/plugins/shipit.py
- ansibullbot/utils/component_tools.py
> Fix unbound local namespace paths

- ansibullbot/triagers/plugins/shipit.py
- ansibullbot/utils/component_tools.py
- tests/unit/utils/test_component_tools.py
Fixes https://github.com/ansible/ansibullbot/issues/1149
WIP till I add some tests.
> Crawl the tree for metadata byte by byte

- ansibullbot/triagers/ansible.py
- ansibullbot/triagers/plugins/deprecation.py
- ansibullbot/utils/webscraper.py
- scripts/list_open_issues_with_deprecated_label.sh
- scripts/scrape_github_issues_url
Fixes https://github.com/ansible/ansibullbot/issues/1155
> move deprecation algo to a plugin

- ansibullbot/parsers/botmetadata.py
- ansibullbot/wrappers/historywrapper.py
- tests/unit/parsers/test_bot_metadata_parser.py
- tests/unit/triagers/plugins/test_shipit.py
Fixes https://github.com/ansible/ansibullbot/issues/1159
> Nullify yaml aliases to prevent pointer overload

- ansibullbot/utils/extractors.py
- tests/unit/utils/test_template_extractor_simple.py
Fixes https://github.com/ansible/ansibullbot/issues/1163
> Use a simpler extraction method by default

- ansibullbot/utils/component_tools.py
- ansibullbot/utils/extractors.py
Fixes https://github.com/ansible/ansibullbot/issues/1169
> Refactor author extraction into something simpler+stabler

- templates/bot_status.j2
Collapse sections in `bot_status` comment.
Preview:
> 'bot_status' comment: collapse sections

- ansibullbot/utils/extractors.py
- ansibullbot/utils/webscraper.py
* the metadata extractor was faulty
* the status bits in the html are no longer a div
> fix two issues

- ansibullbot/decorators/github.py
- ansibullbot/wrappers/defaultwrapper.py
Fixes https://github.com/ansible/ansibullbot/issues/1177
> paginate review fetching

- ansibullbot/triagers/plugins/shipit.py
- tests/unit/triagers/plugins/test_automerge.py
- tests/unit/triagers/plugins/test_shipit.py
FIxes https://github.com/ansible/ansibullbot/issues/1147
> Automerge changelogs

- ansibullbot/utils/shippable_api.py
Fixes https://github.com/ansible/ansibullbot/issues/1194
> Fix posting comments with test results

- playbooks/group_vars/ansibullbot.yml
- playbooks/host_vars/ansibullbot-dev.yml
- playbooks/setup-ansibullbot-dev.yml
- playbooks/setup-ansibullbot.yml
- playbooks/teardown-ansibullbot-dev.yml
- playbooks/vagrant.yml
- revamp and polish integration tests for roles
- add links to the main bot landing page for easier navigation
> Update roles to include changes for bot landing page

- ansibullbot/utils/component_tools.py
> Make sure we have a match object before trying to use it

- ansibullbot/triagers/plugins/component_matching.py
https://github.com/ansible/ansible/issues/56873#issuecomment-495392787
> Process !component even if component is empty

- ansibullbot/triagers/plugins/component_matching.py
Need to ignore the new escape so that we don't spam the component message
> no component spam

- ansibullbot/decorators/github.py
> Catch read timeouts and sleep

- ansibullbot/decorators/github.py
> Catch the retry typeerror and sleep

- ansibullbot/utils/component_tools.py
> Fix "'NoneType' has no len()" in component_tools

- ansibullbot/wrappers/historywrapper.py
> Fix typo in 'ghost' users detection

- ansibullbot/wrappers/defaultwrapper.py
> use logins for merge checking

- ansibullbot/triagers/ansible.py
- ansibullbot/triagers/plugins/cross_references.py
- ansibullbot/utils/gh_gql_client.py
- ansibullbot/wrappers/defaultwrapper.py
- ansibullbot/wrappers/ghapiwrapper.py
- ansibullbot/wrappers/historywrapper.py
- tests/unit/triagers/plugins/test_shipit.py
Fixes https://github.com/ansible/ansibullbot/issues/924
> set has_pr and has_issue labels

- ansibullbot/wrappers/historywrapper.py
- tests/unit/wrappers/test_history_wrapper.py
Fixes https://github.com/ansible/ansibullbot/issues/1244
Fixes https://github.com/ansible/ansibullbot/issues/1243
> Filter out events without timestamps

- ansibullbot/decorators/github.py
- ansibullbot/wrappers/ghapiwrapper.py
- tests/unit/wrappers/test_ghapiwrapper.py
> Ensure ratelimits are handled in the ghapi requestor

- ansibullbot/wrappers/defaultwrapper.py
- constraints.txt
- test-requirements.txt
- tests/unit/wrappers/test_defaultwrapper.py
refixes https://github.com/ansible/ansibullbot/issues/1247
> Invalidate bad cache data and force a refetch

- ansibullbot/wrappers/historywrapper.py
Should fix a lot of the ignored commands and repeated notifications that are happening recently.
> do not use cache if data was reprocessed

- ansibullbot/wrappers/defaultwrapper.py
- ansibullbot/wrappers/ghapiwrapper.py
- ansibullbot/wrappers/historywrapper.py
- tests/component/test_idempotence.py
- tests/utils/componentmocks.py
> Set timestamps for reactions to datetime.datetime

- ansibullbot/wrappers/historywrapper.py
- tests/unit/wrappers/test_history_wrapper.py
Fixes https://github.com/ansible/ansibullbot/issues/1266
> Refix tzinfo fixer

- ansibullbot/triagers/plugins/label_commands.py
- tests/unit/utils/test_component_tools.py
Fixes https://github.com/ansible/ansibullbot/issues/1284
> Skip lines with too few words to be a label command

- ansibullbot/wrappers/defaultwrapper.py
Fixes https://github.com/ansible/ansibullbot/issues/1265
> handle commits with external users

- ansibullbot/triagers/ansible.py
- ansibullbot/utils/component_tools.py
https://github.com/ansible/ansible/issues/68553
> Fixup ap 68553

- ISSUE_HELP.md
- ansibullbot/triagers/ansible.py
- ansibullbot/triagers/plugins/ci_rebuild.py
https://github.com/ansible/ansibullbot/issues/1161
> add /rebuild command for all users

- ISSUE_HELP.md
- ansibullbot/triagers/ansible.py
- ansibullbot/triagers/plugins/ci_rebuild.py
- ansibullbot/utils/shippable_api.py
https://github.com/ansible/ansibullbot/issues/1161
> add /rebuild_failed

- ISSUE_HELP.md
> Add docs on how to stop notifications

- ansibullbot/wrappers/defaultwrapper.py
> Special case status_data for server error

- ansibullbot/triagers/ansible.py
> Delete meta file if not loadable

- ansibullbot/triagers/plugins/small_patch.py
> Prevent potential waffling on small_patch

- ansibullbot/triagers/ansible.py
> Do not tb for invalid resolved_by_pr cmd

- ansibullbot/triagers/ansible.py
- ansibullbot/triagers/plugins/ci_rebuild.py
- tests/unit/triagers/plugins/test_rebuild_merge.py
Related to https://github.com/ansible/ansibullbot/issues/1325
> Set needs_rebuild along with needs_rebuild_all

- ansibullbot/triagers/plugins/needs_info.py
- templates/needs_info_base.j2
- tests/fixtures/needs_info/0_warn_template.yml
- tests/unit/triagers/plugins/test_needs_info.py
> Fix needs_info warn when along with needs_template

- ansibullbot/triagers/ansible.py
> Add needs_triage even if other labels are present

- ansibullbot/triagers/ansible.py
- ansibullbot/triagers/plugins/test_support_plugins.py
- templates/test_support_plugins.j2
Example https://github.com/ansible/ansible/pull/69326#issuecomment-624121538
Fixes #1296
cc @mattclay
> Warn on PRs touching test/support/

- ansibullbot/triagers/defaulttriager.py
- ansibullbot/triagers/plugins/py3.py
- ansibullbot/triagers/plugins/spam.py
- ansibullbot/wrappers/defaultwrapper.py
- ansibullbot/wrappers/historywrapper.py
- tests/unit/triagers/plugins/test_notifications.py
- tests/unit/wrappers/test_defaultwrapper.py
- tests/unit/wrappers/test_history_wrapper.py
- tests/utils/helpers.py
- tests/utils/issue_mock.py
Stop using comments/reactions/events in favor of timeline.
> Refactor HistoryWrapper

- ansibullbot/utils/galaxy.py
These are currently listed in https://github.com/ansible/ansible/labels?q=collection%3A+ with issues and PRs against them. Those they shouldn't have an items
See also https://github.com/ansible/ansibullbot/issues/1372
> More BLACKLIST_FQCNS

- ansibullbot/utils/galaxy.py
> Reduce some false positives in collection matching

- templates/collection_migration.j2
Based on review in today's docs hackathon, we came up with a modification for the first sentence to give a bit more context, based on community review.
> Updating the comment text

- ansibullbot/triagers/ansible.py
> Update comment about 1355

- docs/collection_migration.md
Adding a section on how to migrate PRs manually (at least how to adjust some things in them), and a section on how to find content manually.
CC @samccann
> Update migration docs

- ansibullbot/utils/galaxy.py
This reverts commit 6d5bf2a28fa17f3b641dead921faae9a17b2b264.
> Revert "Rebase collection repos (#1415)"

- ansibullbot/triagers/ansible.py
- ansibullbot/triagers/plugins/shipit.py
> Remove `core_review` when WIP

- ansibullbot/utils/component_tools.py
- ansibullbot/utils/extractors.py
> Component matching fixes

- ansibullbot/triagers/plugins/component_matching.py
- ansibullbot/utils/component_tools.py
- templates/components_banner.j2
> Fix 404 links in the components banner

- ansibullbot/utils/component_tools.py
This reverts commit 86194f9808c4efecefef88a146bc1c63fe73415f.
> Revert "Do not match components partially to prevent matching too much"

- ansibullbot/triagers/plugins/component_matching.py
> Account for whitespaces in !component

- ansibullbot/triagers/plugins/needs_revision.py
> Fix needs_revision command detection

- ansibullbot/triagers/plugins/needs_info.py
> Do not report component missing if !component is used

- README.md
- ansibullbot/constants.py
- ansibullbot/triagers/ansible.py
- ansibullbot/triagers/plugins/ci_rebuild.py
- tests/unit/triagers/plugins/test_rebuild.py
- tests/unit/triagers/plugins/test_rebuild_merge.py
> Add a config option for a CI provider

- azure-pipelines.yml
- pytest.ini
- tox.ini
Fixes https://github.com/ansible/ansibullbot/issues/1432
> Rename shippable to ci_output

- .gitmodules
- scripts/ansibot_status.cgi
- scripts/generate_issues_by_file.py
- minor linting change (not significant)
- Update Flask and Flask-PyMongo to avoid stack trace
- fix proxy config to allow the cgi script run properly
- some SELinux changes to allow the status script to run
- remove cron job to cleanup Shippable cache
- fix incorrect tags
> Fix metadata by file generation script and some changes for status

- .gitmodules
- scripts/ansibot_status.cgi
A whole lot of SELinux wrangling.
> Fix status page

- ISSUE_HELP.md
The same as already done in https://github.com/ansible-community/collection_bot/pull/25
> ISSUE_HELP.md: improve terminology

- ISSUE_HELP.md
ISSUE_HELP.md: Remove ANSIBLE_METADATA related notes
> ISSUE_HELP.md: Remove ANSIBLE_METADATA

- ansibullbot/triagers/ansible.py
- ansibullbot/utils/component_tools.py
- ansibullbot/utils/git_tools.py
Instead of figuring this info out from botmeta, list files from 2.9
branch.
> Pre collections modules in component matcher

- ansibullbot/wrappers/defaultwrapper.py
> Label Draft PRs as WIP

- ansibullbot/utils/component_tools.py
We already go through module files in the checkout.
> Call to ansible-doc is redundant

- ansibullbot/wrappers/defaultwrapper.py
The merge_method wasn't available back then, it is now.
> Use PyGithub API for PR merging

- ansibullbot/triagers/plugins/docs_info.py
> docs_only: skip if deletions only

- pytest.ini
Ref: https://pganssle-talks.github.io/xfail-lightning
> Follow pytest best practice of strict xfail

- .gitmodules
- playbooks/host_vars/ansibullbot-dev.eng.ansible.com.yml
- playbooks/host_vars/ansibullbot.eng.ansible.com.yml
Switch role tests to use AZP.
Set host vars for `azp['definition']`
> Update ansibullbot role and define AZP definition

- ansibullbot/triagers/ansible.py
- ansibullbot/triagers/plugins/contributors.py
- ansibullbot/wrappers/defaultwrapper.py
- tests/utils/helpers.py
- tests/utils/issue_mock.py
> DefaultWrapper.pullrequest_status is no longer needed

- ansibullbot/triagers/ansible.py
Seems like it was only for debugging?
> Uses built-in dict instead of MetaDict

- ansibullbot/utils/version_tools.py
origin/2.11 broke version detection in ansible_version_by_commit so fix
this and refactor the method while in there.
> Fix ansible_version_by_commit to account for origin/2.11

- templates/bad_pr.j2
- templates/test_support_plugins.j2
Extends https://github.com/ansible/ansibullbot/pull/1577.
> Change Freenode refrences to Libera
