ansible/ansibullbot

- MAINTAINERS-EXTRAS.txt
- prbot.py
I implemented github private token support, useful if you enabled 2fa
(you should...). You can then just pass --ghtoken <token> to the cli.
Find more about gh token here
https://help.github.com/articles/creating-an-access-token-for-command-line-use/
Further I implemented support for "namespaces":
e.g. cloud/cloudstack/: resmo
This means I would also be added as maintainer for any PR in this namespace.
> github token and namespace support in PR bot

- MAINTAINERS-EXTRAS.txt
- prbot.py
e.g. cloud/cloudstack/ is resmo's maintainer namespace
I made the commit small and self explaining, only implementing namespacing. Tested it and worked for me. Thanks @gregdek 
```
1591 --- [2.1] cloudstack: new module cs_zone
Labels:  [u'cloud', u'new_plugin', u'owner_pr']
Submitter:  resmo
Maintainer(s): resmo
Filename(s):  cloud/cloudstack/cs_zone.py
RECOMMENDED ACTIONS for  https://github.com/ansible/ansible-modules-extras/pull/1591
newlabel: shipit
newlabel: owner_pr
boilerplate: shipit_owner_pr
```
> namespace support for maintainers

- templates/backport.j2
- templates/community_review_existing.j2
- templates/community_review_new.j2
- templates/core_review_existing.j2
- templates/maintainer_first_warning.j2
- templates/maintainer_second_warning.j2
- templates/needs_rebase.j2
- templates/needs_revision.j2
- templates/shipit.j2
- templates/shipit_owner_pr.j2
- templates/submitter_first_warning.j2
- templates/submitter_second_warning.j2
- triage.py
@gregdek please give it a shot. 
Did not test the API calls for creating, removing labels and adding comments but it _should_ work.
As the previous bot, it asks and prints the actions before doing any work. Use `-v` for more verbosity. I also implemented `-f` for non-interactive mode. This may be useful for webhooks (or travis) on a new PRs event.
~~~
$ pip install pygithub
$ ./triage.py 
usage: triage.py [-h] [--gh-user GH_USER] [--gh-pass GH_PASS]
[--gh-token GH_TOKEN] [--verbose] [--force] [--debug]
[--pause] [--pr PR] [--start-at START_AT]
{core,extras}
~~~
E.g.
~~~
$ ./triage.py --gh-user gregdek --gh-pass <your_pass>  extras -v
~~~
> new triage

- triage.py
we used lowercase in the maintainers files but the real username may contain capital letters
> fix maintainer user name not detected if has capital letters

- triage.py
we often get a unknown state from the api for mergeable. I don't see why, but this is a workaround.
> workaround for unknown mergeable state

- templates/community_review_owner_pr.j2
- templates/shipit_owner_pr.j2
- triage.py
Closes #54
@gregdek: FYI, found 2 PR e1370 and e1931 where I quick removed owner_pr and then ran the bot, which gave the result wanted.
actually I noticed the owner_pr is not even needed... we can get rid of if you like, I would keep it.
> triage: implement new owner_pr process

- triage.py
/cc @gregdek problem identified and fixed, no description results in a None type body.
fixes #89
~~~
PR #3026: authorized_key: support --diff
Created at 2016-02-12 11:48:12
Updated at 2016-02-23 16:06:46
Debug: Forced core review, skipping maintainer
Debug: --- START Processing Comments:
Debug: robynbergeron is in botlist: 
Debug: Days since last bot comment: 54
Debug: has core_review
Debug: --- END Processing Comments
Debug: PR is mergeable
Debug: Build state is success
Debug: PR has no description
Submitter: mgedmin
Maintainers: ansible
Current Labels: core_review, feature_pull_request
Actions: {'newlabel': [], 'comments': [], 'unlabel': []}
Skipping.
~~~
> implement labels by issue type

- triage.py
suggested implementation for #73 
/cc @gregdek
~~~
PR #2007: Added pvs parameter to lvol module
Created at 2016-04-11 18:47:40
Updated at 2016-04-16 12:16:33
Debug: PR is mergeable
Debug: shipit labeled, skipping maintainer
Debug: --- START Processing Comments:
Debug: resmo is a ansible member
Debug: ...said needs_revision!
Debug: --- END Processing Comments
Debug: Build state is success
Debug: Thanks @p53 for this PR. This PR requires revisions, either because it fails to build or by reviewer request. Please make the suggested revisions. When you are done, please comment with text 'ready_for_review' and we will put this PR back into review.
[This message brought to you by your friendly Ansibull-bot.]
Submitter: p53
Maintainers: jhoekx, abulimov
Current Labels: shipit
Actions: …
> put labels according ansible member comments

- MAINTAINERS-CORE.txt
As I'm now part of the Networking Team I need to be aware of what's going on.
On review I also noticed a few directories were missing so added these, as per discussion with Peter
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ansible/ansibullbot/114)
> network/ maintainers - add missing - add gundalow

- MAINTAINERS-CORE.txt
With a double space you get:
(@privateip, @, @gundalow, @chouseknecht, @privateip, @gundalow)
I'll raise a bug https://github.com/ansible/ansibullbot/issues/116 to fix the parser
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ansible/ansibullbot/117)
> Remove double spaces which confuse Ansibull-bot

- MAINTAINERS-CORE.txt
chouseknecht wrote some of the modules, however it's Peter and I that now maintain them.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ansible/ansibullbot/135)
> Remove chouseknecht as network maintainer

- MAINTAINERS-EXTRAS.txt
@linuxdynasty you were not set as the maintainer which is why you didn't get pinged on https://github.com/ansible/ansible-modules-extras/pull/2828/files
> cloud/amazon/kinesis_stream.py linuxdynasty

- MAINTAINERS-EXTRAS.txt
tanpeter is ceding ownership of the gce_img module as Tom has been actively working on the other Google modules.
> Move ownership of gce_img module

- MAINTAINERS-EXTRAS.txt
undo change made by https://github.com/ansible/ansibullbot/commit/ae4cf905c3a5de59eca414d69e0a37f79a7dfdf5
> Set global maintainer for vmware back to chrrrles

- lib/utils/extractors.py
- lib/wrappers/defaultwrapper.py
The ondisk cache for comments and events had an extra directory. This moves those files to the right place and cleans up.
> Fix cache loc

- lib/utils/extractors.py
Instead, use re to locate the module string and pull it out with list comprehension.
Fixes #198
> Some modules have _module in their name, and we can't just strip it.

- MAINTAINERS-CORE.txt
As discussed in
https://github.com/ansible/ansible-modules-core/pull/5454#issuecomment-257960268
@n0trax should be added as maintainer of apache2_module
@n0trax is very active in answering issues, reviewing pull requests and did a major rewrite of the module already in https://github.com/ansible/ansible-modules-core/pull/2417
> Add n0trax as apache2_module maintainer

- lib/utils/extractors.py
```
Issue #18757 [0]: Fix link from dynamic inventory page to dev guide page
https://github.com/ansible/ansible/pull/18757
Created at 2016-12-05 21:15:28
Updated at 2016-12-05 21:15:28
File "./triage.py", line 892, in <module>
main()
File "./triage.py", line 868, in main
triage.run()
File "/home/jtanner/workspace/github/jctanner/ansibullbot.prod/lib/triagers/pulltriager.py", line 83, in run
self.process()
File "/home/jtanner/workspace/github/jctanner/ansibullbot.prod/lib/triagers/ansible_ansible_pulltriager.py", line 127, in process
self._process()
File "/home/jtanner/workspace/github/jctanner/ansibullbot.prod/lib/triagers/defaulttriager.py", line 176, in _process
self.template_data = self.issue.get_template_data()
File …
```
> Fix Nonetype attribute error

- MAINTAINERS.txt
This patch updates the F5 modules so that F5 devs are the maintainers
for all of them and so that the community contributors are no longer
on the hook for their support
> Updates maintainers to add F5 devs for all F5 modules

- MAINTAINERS.txt
romeotheriault doesn't exist on GitHub anymore (or there is a typo in the module *and* this file)
Eitherway this is a `'supported_by': 'core'` module, so proposing we take ownership of it
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ansible/ansibullbot/291)
> uri -> ansible

- MAINTAINERS.txt
If a module under cloud/amazon has no maintainer, willthames
will be maintainer by default
> Make willthames fallthrough maintainer for cloud/amazon

- MAINTAINERS.txt
Removing @zimbatm from AWS maintainers list at his request. I have left him as maintainer on notifications/grove as that will be far less likely to cause a deluge of traffic
See ansible/ansible#19787
> Remove zimbatm from AWS module owners

- MAINTAINERS.txt
As requested by timuster (ksumit on IRC)
`[20:03] < ksumit> @gundalow Can you also add lmprice to the maintainers list? So the lsit should be changed to hulquest + timuster + lmprice`
> storage/netapp -> hulquest timuster lmprice 370

- lib/triagers/ansible.py
to prevent pinging them with the "namespace maintainer" template.
> Remove submitter from community list after shipit calculations

- MAINTAINERS.txt
Previously we were notifying a group (GitHub org) which worked, though Ansibot doesn't know is in that group, so we didn't get owner_pr, etc set.
https://github.com/ansible/ansible/pull/21101#issuecomment-280040472
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ansible/ansibullbot/373)
> network/cumulus/: notify individuals not the group

- lib/triagers/ansible.py
[ISSUE_HELP.md](https://github.com/pilou-/ansibullbot/blob/allow_submitter_to_use_bot_status/ISSUE_HELP.md) states that submitters are allowed to use `bot_status`, so be it.
> Allow submitter to use bot_status command

- lib/triagers/ansible.py
The method `get_valid_labels` is called twice unnecessarily.
> Fetch valid labels only once

- lib/triagers/ansible.py
Because all repositories are checked, `issue` could be `None` when using `--pr` parameter
> Avoid exception when 'pr' switch is used.

- MAINTAINERS.txt
mhite has a long and storied past with the F5 modules, but in his
day-to-day work he deals with them much less and caphrim007, who
works at F5, has volunteered to take over the maintenance of all
the modules. Removing him so that he's not notified of future
issues/prs
> Removing maintainer

- MAINTAINERS.txt
> add missing s3_sync owner

- MAINTAINERS.txt
Add Cisco's mikewiebe as a maintainer of the NXOS modules so he will be notified of issues and PRs. This will allow his `shipit` comments to be counted.
> network/nxos + mikewiebe

- MAINTAINERS.txt
https://github.com/ansible/ansible/pull/24080
Wimnat is the author of the module but isn't in the maintainers list. He wants to be notified for PRs impacting iam_role.
> add wimnat as maintainer for iam_role

- MAINTAINERS.txt
Since Tom is moving teams, make erjohnso the maintainer for the GCP namespace so he's looped in on issues.
> Move namespace for GCP modules to Eric

- lib/decorators/github.py
* don't assume that rate limit response contain usable information
* [some code assumes](https://github.com/ansible/ansibullbot/blob/6fbf34c8c815b655b547bfa0e402cddec97df0b4/lib/decorators/github.py#L41) that `get_rate_limit` might return a `False` expression: improve consistency
> Don't fail when rate limit response doesn't contain requested information, improve consistency

- lib/triagers/defaulttriager.py
Currently, the following command fails:
```
$ ./triage_ansible.py --dry-run --verbose --pr 24625 --logfile log.txt
File "./triage_ansible.py", line 117, in <module>
main()
File "./triage_ansible.py", line 113, in main
AnsibleTriage(args).start()
File "/home/pilou/ansibullbot/lib/triagers/ansible.py", line 219, in __init__
self.set_logger()
File "/home/pilou/ansibullbot/lib/triagers/defaulttriager.py", line 261, in set_logger
os.makedirs(logdir)
File "/home/pilou/.v/ansibot2/lib/python2.7/os.py", line 157, in makedirs
mkdir(name, mode)
OSError: [Errno 2] No such file or directory: ''
```
> Allow to use log file located in current directory

- MAINTAINERS.txt
Since there is a Netscaler module in ansible 2.4 I am adding the maintainers for it and the upcoming modules.
Cheers
> Add giorgos-nikolopoulos and chiradeep as network/netscaler/ maintainers

- MAINTAINERS.txt
I talked to rwaweber at pycon and he was interested in helping to maintain the linode module (he presently works for linode).  Pull request here to add him as a comaintainer of the module.
> Add rwaweber as a linode maintainer

- MAINTAINERS.txt
I noticed this was missing.  I am the original author and suggest I be listed as the maintainer.
> Add pamd.py maintainter

- lib/triagers/ansible.py
```
2017-06-29 00:14:42,085 DEBUG https://api.github.com:443 "GET /rate_limit HTTP/1.1" 200 None
2017-06-29 00:14:42,104 DEBUG ratelimited call #1 [<class 'lib.wrappers.issuewrapper.IssueWrapper'>] [get_labels] [2861]
File "./triage_ansible.py", line 117, in <module>
main()
File "./triage_ansible.py", line 113, in main
AnsibleTriage(args).start()
File "/home/ansibot/ansibullbot/lib/triagers/defaulttriager.py", line 278, in start
self.loop()
File "/home/ansibot/ansibullbot/lib/triagers/defaulttriager.py", line 763, in loop
self.run()
File "/home/ansibot/ansibullbot/lib/triagers/ansible.py", line 494, in run
self.create_actions()
File "/home/ansibot/ansibullbot/lib/triagers/ansible.py", line 1240, in create_actions
sb = …
```
> Use core if no supported_by

- MAINTAINERS.txt
We will shortly be moving the Ansible 2.4 Network modules around, ensure the owners are set
> Add new Network topics

- MAINTAINERS.txt
The Digital Ocean cloud module has become stale and maintainers appear to have moved on to newer and bigger things. I would like to help reignite the Digital Ocean module development. Currently we have 5 different PRs that have been setting for a while. The DO API has introduced a number of new features that need modules or enhancements. Speeding up development on these DO modules will hopefully keep Ansible relevant in the DO community.
> Add bondanthony as digital_ocean maintainer

- ISSUE_HELP.md
This pull request updates `ISSUE_HELP.md`:
- add a table of content
- state show `approve` pull request status is ignored
- describe community from a bot point of view
- including:
- fix broken links
- add links
- list: fix indentation of content
- remove trailing spaces
> ISSUE_HELP.md, add info: 'approve' PR status ignored, community members from bot's point of view

- ansibullbot/constants.py
- ansibullbot/decorators/github.py
- ansibullbot/triagers/defaulttriager.py
This pull-request fix a HTTP 401 error (`Bad credentials`) which occurs when token is not set.
The cause of this error was this invalid HTTP header:
```{'Authorization': 'Bearer False', 'Accept': 'application/json'}```.
> config: use boolean type, fix default string values

- ansibullbot/triagers/ansible.py
- ansibullbot/utils/shippable_api.py
This pull-request allow to automatically re-run CI on pull-request labeled with both `shipit` and `stale_ci`.
This will facilitate contributors and maintainers workflows when a pull-request is labeled with `stale_ci`, avoiding submitter:
1. to rebase the branch pull-request in order to trigger the CI and to remove the `stale_ci` label;
2. to ask maintainer who had already approved a pull-request using the `shipit` command to use again the `shipit` command (because `shipit` counters are reset after a rebase).
I was not able to test (on a custom project) the HTTP request to `projects/{projectId}/newBuild`, this Shippable API [isn't usable](https://github.com/Shippable/support/issues/3628#issuecomment-305091311) using a free Shippable account.
Related: #459 #460
> re-run CI on stalled pull-request with 'shipit'

- ansibullbot/triagers/plugins/ci_rebuild.py
- ansibullbot/triagers/plugins/shipit.py
This behavior was added by 369232a7d1285361b4e7d2d7902b763b9767e514, don't prevent it. See #659.
> Allows automerge when deletion in sanity text files

- ansibullbot/triagers/ansible.py
- ansibullbot/triagers/defaulttriager.py
- triage_ansible.py
If used, each issue number will be recorded to a json file in the cachedir
when processing begins. If the bot is stopped or dies, on the next run,
it will read the json file, decrement the number and set args.start_at
This effectively resumes processing and skips the issue that is broken,
and gives a smoother experience when combined with a systemd autorestart.
> Adds the --resume argument to triage_ansible.py

- ansibullbot/utils/moduletools.py
- tests/unit/utils/test_githubid_extractor.py
Relates to #704.
Add support for:
- multiple GitHub IDs in one line: `team (@user1, @user2)` (used in [identity/cyberark/cyberark_user.py](https://github.com/ansible/ansible/blob/devel/lib/ansible/modules/identity/cyberark/cyberark_user.py#L16))
- GitHub IDs not surrounded by parentheses: `Name @id` (used in https://github.com/ansible/ansible/blob/devel/lib/ansible/modules/system/java_cert.py#L57)
> Search authors using other formats

- ansibullbot/triagers/ansible.py
- ansibullbot/utils/gh_gql_client.py
- ansibullbot/utils/moduletools.py
- requirements.txt
- tests/unit/utils/test_githubid_extractor.py
The purpose of this pull request is to avoid to add module author in `.github/BOTMETA.yml` when `DOCUMENTATION.author` contains an email address but not an GitHub ID. `.github/BOTMETA.yml` should only be used when authors and maintainers differ (and `DOCUMENTATION.author` should contain GitHub ID).
Not that because `.github/BOTMETA.yml` already contains an entry for each module where `DOCUMENTATION.author` contains an email address but not an GitHub ID, nothing will change. But some entries in `.github/BOTMETA.yml` could be removed (the ones for which module authors and module maintainers are the same and `DOCUMENTATION.author` contains email address).
Commits explanation:
- second commit: implement `get_usernames_from_filename_blame` using GraphQL (allowing to map email address and …
> Find GitHub ID searching for email

- ansibullbot/triagers/plugins/needs_revision.py
- ansibullbot/wrappers/historywrapper.py
ansibot do not review pull requests but it fixes a potential exception when the bot is run locally:
```
File "ansibullbot/wrappers/historywrapper.py", line 649, in merge_reviews
event['created_at'] = self.parse_timestamp(review['submitted_at'])
KeyError: 'submitted_at'
```
> Handle PENGING reviews

- ansibullbot/triagers/ansible.py
When `--pr` switch is specified, Ansible triager tried to process the issue in all known repositories, even if issue exist in only one repository.
> Use 'pr' value only if issue/pr exists

- ansibullbot/triagers/ansible.py
- ansibullbot/wrappers/defaultwrapper.py
This pull request allows to use `--ignore_state` switch.
Note that `--ignore_state` switch is useful while debugging, however plugins might return inconsistent values when a closed pull request is processed: `--ignore_state` should not be used without `--dry-run`.
> Handle closed pull requests (`mergeable_state` of merged pull requests is `unknown`)

- ansibullbot/triagers/ansible.py
Many issues are getting duplicate notification and label events in a very small time window.
https://github.com/ansible/ansible/pull/29033
https://github.com/ansible/ansibullbot/commit/896405fa0c1a90da13a9510e3426f4552c723c91 removed unique'ing on the numbers from the repoiterator which has probably caused some issues to run twice in the same loop and possibly hit race conditions on labeling.
> fix duplicate actions by unique'ing the list of numbers

- templates/bot_status.j2
In `bot_status` comment:
- add `shipit_actors_other`
- add a description for `shipit` fields
- labels: add links to documentation
- add link to `supported_by` documentation
> Add informations in bot status comment

- ansibullbot/triagers/ansible.py
This cuts down on label waffling and unexpected bot deaths.
> Ignore [un]labeling *_review if the PR is a WIP.

- ansibullbot/triagers/ansible.py
Fix a typo.
When `meta.json` is read, `assignees` isn't used: there is no need to handle rename.
> Fix typo s/assigees/assignees/

- ansibullbot/triagers/ansible.py
- ansibullbot/triagers/defaulttriager.py
> Improve usage of argparse.Namespace

- ansibullbot/triagers/defaulttriager.py
- ansibullbot/triagers/simpletriager.py
- `SimpleTriager`: use `file_indexer` parameter with `IssueWrapper`
- remove unused `DefaultTriager.wrap_issue`
> SimpleIndexer: use file_indexer with IssueWrapper

- ansibullbot/triagers/ansible.py
- ansibullbot/utils/moduletools.py
```
2017-09-11 18:31:29,897 DEBUG ratelimited call #1 [<class 'ansibullbot.wrappers.ghapiwrapper.RepoWrapper'>] [get_repo] [4963]
2017-09-11 18:31:29,897 INFO getting issue objs for ansible/ansible-modules-extras
2017-09-11 18:31:29,899 DEBUG ansible/ansible-modules-extras issues pagecount:0 nodecount: 0
2017-09-11 18:31:29,900 INFO Starting new HTTPS connection (1): api.github.com
2017-09-11 18:31:30,008 DEBUG "POST /graphql HTTP/1.1" 200 None
2017-09-11 18:31:30,012 DEBUG ansible/ansible-modules-extras pullRequests pagecount:0 nodecount: 0
2017-09-11 18:31:30,013 INFO Starting new HTTPS connection (1): api.github.com
2017-09-11 18:31:30,194 DEBUG "POST /graphql HTTP/1.1" 200 None
2017-09-11 18:31:30,197 INFO 0 known numbers
2017-09-11 18:31:30,197 ERROR list index out of range …
```
> Fix traceback in daemonize mode

- ansibullbot/wrappers/ghapiwrapper.py
After running `python ./triage_ansible.py --dry-run --logfile /tmp/ansibot --daemonize`  over ~6 hours:
<pre>
$ find ~/.ansibullbot/cache -iname issues
.ansibullbot/cache/cmprescott/ansible-xml/issues
.ansibullbot/cache/ansible/ansible-modules-core/issues
.ansibullbot/cache/ansible/ansible/issues
.ansibullbot/cache/ansible/ansible-modules-extras/issues
</pre>
Closes #759
> Fix pickle path for issues

- ansibullbot/parsers/botmetadata.py
- ansibullbot/triagers/ansible.py
- ansibullbot/utils/moduletools.py
- tests/unit/parsers/test_bot_metadata_parser.py
- tests/unit/utils/test_module_indexer.py
When:
1. a module path without an entry in `BOTMETA.yml` (for example `lib/ansible/modules/packaging/os/xbps.py`)
2. contains another unrelated entry present in `BOTMETA.yml` (for example `packaging/`)
3. then maintainers of the `BOTMETA.yml` entry are added to module maintainers
This pull request:
- add unit test
- improve match: fix this issue
> Fix 'best match' in 'ModuleIndexer': avoid to mix maintainers

- ISSUE_HELP.md
Also, I think we should rename "ansibullbot" into "ansibot" in the documentation, as that's what most people will see. Using a different name for the same thing will make people wonder whether this is something different.
> Add auto-labeling to the list of things ansibot does

- ansibullbot/triagers/plugins/shipit.py
- tests/unit/triagers/plugins/test_shipit.py
This pull request prevents `shipit` label to be added when `needs_rebase` or `needs_revision` label is already set.
Unit tests provided.
Closes #783
> needs_rebase and needs_revision prevent shipit label to be added

- ansibullbot/utils/extractors.py
- tests/unit/utils/test_template_extractor.py
Create function for scrubbing bad characters with a few exceptions based on regular expressions.
Add additional test for when Markdown headers have the option `####` at the end of the line.
> Fix test_template_extractor test_2

- ansibullbot/triagers/plugins/shipit.py
- ansibullbot/utils/moduletools.py
- tests/unit/triagers/plugins/test_shipit.py
- tests/unit/utils/test_module_indexer.py
- tests/utils/module_indexer_mock.py
This pull request allows to:
- set `owner_pr` label when pull request updates file below `lib/ansible/module_utils` and submitter is maintainer of these file
- set `owner_pr` only when submitter if maintainer of each updated files (see https://github.com/ansible/ansibullbot/issues/776#issuecomment-334428396)
- `owner_pr` won't be set if an updated file isn't below `lib/ansible/module_utils` or `lib/ansible/modules` is modified
Unit tests provided.
Closes #776
> set owner_pr when only when submitter is maintainer of all modified files, handle module_utils

- ansibullbot/utils/gh_gql_client.py
GitHub's GraphQL can return 200s with errors, if say the schema
submitted to it was invalid. This can break anything trying to make use
of the json data and expecting real values and structure. This bit of
code will detect when errors come back and will do a raise.
> Handle GraphQL errors on a status 200

- ansibullbot/decorators/github.py
> If "No handler found for uri" in message, try sleeping for 2 minutes as a workaround.

- ansibullbot/triagers/plugins/notifications.py
Another fix could be to test `self.meta.get('merge_commits')` in [`create_actions`](https://github.com/pilou-/ansibullbot/blob/dont_notify_if_there_is_a_merge_commit/ansibullbot/triagers/ansible.py#L1050) but this method is already long enough.
Tested manually using both a pull-request and an issue:
```
./triage_ansible.py --dry-run --logfile /tmp/bot.log --pr 32576 # no notification
./triage_ansible.py --dry-run --logfile /tmp/bot.log --pr 30599 # no exception
```
Fixes #787
> Don't notify anyone when branch contains a merge commit

- ansibullbot/utils/component_tools.py
and then remove them in one fell swoop from the namespace.
Fixes https://github.com/ansible/ansibullbot/issues/819
> Keep track of all maintainers in namespace who wish to be ignored,

- ansibullbot/wrappers/defaultwrapper.py
This is a partial fix for https://github.com/ansible/ansibullbot/issues/856. The remaining part is to go through the issues that ping ansibot for response, ping the original submitter instead and set needs info back.
> Figure out original issue submitter

- ansibullbot/triagers/plugins/needs_revision.py
- ansibullbot/utils/webscraper.py
fixes https://github.com/ansible/ansibullbot/issues/861
also fixes ...
```
2018-02-13 12:05:02,385 INFO ansible version: 2.6.0devel
2018-02-13 12:05:02,386 INFO Starting new HTTPS connection (1): api.github.com
2018-02-13 12:05:02,489 DEBUG "GET /rate_limit HTTP/1.1" 200 None
2018-02-13 12:05:02,493 DEBUG ratelimited call #1 [<class 'ansibullbot.wrappers.issuewrapper.IssueWrapper'>] [load_update_fetch] [2112]
2018-02-13 12:05:02,496 INFO Starting new HTTPS connection (1): api.github.com
2018-02-13 12:05:02,612 DEBUG "GET /rate_limit HTTP/1.1" 200 None
2018-02-13 12:05:02,617 DEBUG ratelimited call #1 [<class 'ansibullbot.wrappers.issuewrapper.IssueWrapper'>] [pullrequest_raw_data] [2112]
2018-02-13 12:05:02,617 INFO pullrequest_status load pfile
2018-02-13 12:05:02,617 ERROR Uncaught …
```
> Fixes a few recent tracebacks

- ansibullbot/triagers/ansible.py
- ansibullbot/triagers/plugins/performance.py
Allows for easier tracking of performance issues/PRs.
Tested on:
https://github.com/ansible/ansible/issues/36431 (`performance` in `body`)
https://github.com/ansible/ansible/issues/32678 (`performance` in `title`)
https://github.com/ansible/ansible/pull/36626 (no `performance`)
> Make bot add performance label

- ansibullbot/triagers/ansible.py
Just use a single label `docs` not `docs_pull_request` or `docs_request`
See https://github.com/ansible/ansible/pull/36757
> `documentation report` & `docs pull request` should add label:docs

- ansibullbot/triagers/plugins/needs_info.py
I think this https://github.com/ansible/ansibullbot/pull/888/files#diff-c047accbde02f1182f15063bdcc95291R139 caused all newly created issues got `needs_info`, e.g.:
https://github.com/ansible/ansible/pull/37594
> Remove is_needs_info debug

- templates/multiple_module_notify.j2
The current link takes people to https://docs.ansible.com/ansible/latest/dev_guide/index.html instead of to the correct documentation page, making it somewhat difficult to track down the actual documentation that it's supposed to be referencing.
> Update multiple module template

- ansibullbot/utils/receiver_client.py
```
2018-05-15 07:51:32,281 INFO RECEIVER: POST to http://127.0.0.1:5001/metadata
2018-05-15 07:51:32,282 INFO Starting new HTTP connection (1): 127.0.0.1
2018-05-15 07:51:32,313 DEBUG "POST /metadata?repo=ansible&user=ansible&number=40070 HTTP/1.1" 500 None
2018-05-15 07:51:32,314 ERROR Uncaught exception
main()
self.loop()
self.run()
File "/home/ansibot/ansibullbot/ansibullbot/triagers/ansible.py", line 448, …
```
> receiver_client: No JSON object could be decoded

- ISSUE_HELP.md
- templates/community_review_existing.j2
- templates/core_review_existing.j2
- templates/issue_invalid_module.j2
- templates/merge_commit_notify.j2
- templates/multiple_module_notify.j2
- templates/needs_revision_not_mergeable.j2
- templates/new_issue_alert.j2
- templates/no_shippable_yaml.j2
- templates/repomerge.j2
- templates/repomerge_new.j2
- templates/travis_notify.j2
As PRs go into the devel branch, contributors should be following the
devel guides, rather than the "latest" stable release.
Ensure ensure that we link to direct pages, rather than requiring
redirects.
> Link to devel docs

- ansibullbot/triagers/plugins/ci_rebuild.py
```
main()
self.loop()
self.run()
File "/home/ansibot/ansibullbot/ansibullbot/triagers/ansible.py", line 443, in run
File "/home/ansibot/ansibullbot/ansibullbot/triagers/ansible.py", line 1908, in process
self.meta.update(get_ci_facts(iw))
File "/home/ansibot/ansibullbot/ansibullbot/triagers/plugins/ci_rebuild.py", line 37, in get_ci_facts
pr_status = [x for x in iw.pullrequest_status]
File …
```
> Don't get CI facts on issues

- ansibullbot/wrappers/historywrapper.py
https://github.com/ansible/ansible/pull/40785
```
main()
self.loop()
self.run()
File "/home/ansibot/ansibullbot/ansibullbot/triagers/ansible.py", line 453, in run
self.save_meta(iw, self.meta, actions)
File "/home/ansibot/ansibullbot/ansibullbot/triagers/ansible.py", line 635, in save_meta
self.dump_meta(issuewrapper, dmeta)
File "/home/ansibot/ansibullbot/ansibullbot/triagers/ansible.py", line 723, in dump_meta …
```
> Fix json error on NamedUser

- ansibullbot/triagers/ansible.py
- ansibullbot/triagers/plugins/small_patch.py
Fixes https://github.com/ansible/ansibullbot/issues/393
Will add tests once we agree on the starter heuristic.
@abadger proposed the following in the issue:
> * no more than two hunks of code are changed.
> * Each hunk should be at most three lines changed.
I could not figure out how to count changes in each chunk in a sane way so the code does the following:
* any new or deleted files in a PR are not classified as `small_patch`
* each modified file in a PR can change 6 lines at most (additions and deletions)
* tests are not counted as a change, see PR I tested on below (but PRs only containing tests are not `small_patch`)
* PR can have two chunks of changed code at most
So if I have not confused myself, the biggest `small_patch` could be two changed files with 6 added lines in each. …
> [RFC] Add small_patch label

- ansibullbot/triagers/plugins/component_matching.py
```
2018-07-24 15:58:28,088 INFO starting triage for https://github.com/ansible/ansible/issues/42977
File "/home/ansibot/ansibullbot/triage_ansible.py", line 42, in 
main()
self.loop()
self.run()
File "/home/ansibot/ansibullbot/ansibullbot/triagers/ansible.py", line 445, in run
File "/home/ansibot/ansibullbot/ansibullbot/triagers/ansible.py", line 1827, in process
self.valid_labels
File "/home/ansibot/ansibullbot/ansibullbot/triagers/plugins/component_matching.py", …
```
> Fix 'NoneType' object has no attribute 'group'

- ansible.cfg
Looks like this role was a bit behind. Mainly adding tasks to `monitoring.yml` that allow the `apache` user to read the ansibullbot code checkout so it can display it in the status page.
> Update ansibullbot role

- ansibullbot/decorators/github.py
```
2018-08-06 05:07:40,173 INFO starting triage for https://github.com/ansible/ansible/pull/43671
File "/home/ansibot/ansibullbot/triage_ansible.py", line 42, in 
main()
self.loop()
self.run()
File "/home/ansibot/ansibullbot/ansibullbot/triagers/ansible.py", line 438, in run
iw.update_pullrequest()
File "/home/ansibot/ansibullbot/ansibullbot/wrappers/defaultwrapper.py", line 880, in update_pullrequest
self._pr = self.repo.get_pullrequest(self.number)
File …
```
> Fix NoneType exception in RateLimited

- ansibullbot/wrappers/defaultwrapper.py
Some failures are due to `405 Method Not Allowed` `You're not authorized to push to this branch.` like if someone does `rebuild_merge` on a backport PR. So just log this info into exception so we don't have to investigate.
> Better info in 'merge failed' exception

- ansibullbot/triagers/plugins/notifications.py
With this I am hoping to get rid of the following traceback that we've been getting a lot:
```
2018-09-06 13:15:43,844 INFO starting triage for https://github.com/ansible/ansible/pull/45287
File "/home/ansibot/ansibullbot/triage_ansible.py", line 42, in 
main()
self.loop()
self.run()
File "/home/ansibot/ansibullbot/ansibullbot/triagers/ansible.py", line 446, in run
File "/home/ansibot/ansibullbot/ansibullbot/triagers/ansible.py", line 1876, in process …
```
> Use has_in_assignees instead of fetching them all

- ansibullbot/utils/component_tools.py
It's `notified`, not `notify`: https://github.com/ansible/ansible/blob/devel/.github/BOTMETA.yml#L26
This requires a fix in BOTMETA, I'll send a PR shortly.
Tested on https://github.com/ansible/ansible/issues/38436
> Fix notified key in BOTMETA

- ansibullbot/triagers/ansible.py
For example [here](https://github.com/ansible/ansible/pull/45554), Ansibot adds the `bad_pr` comment every time the issue is processed.
> Add bad_pr comment only if comment hasn't been added since last commit

- ansibullbot/triagers/ansible.py
Fixes #1037
@pilou- I think it's better to just post the comment once when `bad_pr` is detected and never again.
> Post bad_pr comment just once

- ansibullbot/utils/component_tools.py
```
2018-10-02 03:47:16,621 INFO starting triage for https://github.com/ansible/ansible/pull/42720
File "/home/ansibot/ansibullbot/triage_ansible.py", line 42, in 
main()
File "/home/ansibot/ansibullbot/ansibullbot/triagers/defaulttriager.py", line 181, in start
self.loop()
File "/home/ansibot/ansibullbot/ansibullbot/triagers/defaulttriager.py", line 292, in loop
self.run()
File "/home/ansibot/ansibullbot/ansibullbot/triagers/ansible.py", line 456, in run
File "/home/ansibot/ansibullbot/ansibullbot/triagers/ansible.py", line 1858, in process
self.valid_labels
File "/home/ansibot/ansibullbot/ansibullbot/triagers/plugins/component_matching.py", …
```
> Fix issue with missing support bit

- ansibullbot/triagers/ansible.py
- templates/notify.j2
Because Ansible documentation states that `Ansibullbot serves many functions: - Responds quickly to PR submitters to thank them for submitting their PR [...]` ([here](https://docs.ansible.com/ansible/devel/community/development_process.html#overview)).
> Thanks contributors for submitting their PR

- ansibullbot/utils/shippable_api.py
```
2018-10-08 16:46:34,439 ERROR Uncaught exception
main()
File "/home/ansibot/ansibullbot/ansibullbot/triagers/defaulttriager.py", line 184, in start
self.loop()
File "/home/ansibot/ansibullbot/ansibullbot/triagers/defaulttriager.py", line 295, in loop
self.run()
File "/home/ansibot/ansibullbot/ansibullbot/triagers/ansible.py", line 426, in run
lsr = self.SR.get_last_completion(iw.number)
File "/home/ansibot/ansibullbot/ansibullbot/utils/shippable_api.py", line 112, in get_last_completion
nruns = self.get_pullrequest_runs(number)
File …
```
> Fix import syntax

- ansibullbot/decorators/github.py
- ansibullbot/triagers/ansible.py
```
2018-10-08 17:46:05,622 INFO 46634 known numbers
2018-10-08 17:46:06,570 INFO 2 numbers after [api] since == 2018-10-08 17:32:08
2018-10-08 17:46:06,781 INFO 2 numbers after [www] since == 2018-10-08 17:32:08
2018-10-08 17:46:06,789 ERROR No JSON object could be decoded
2018-10-08 17:46:06,791 ERROR Uncaught exception
main()
File "/home/ansibot/ansibullbot/ansibullbot/triagers/defaulttriager.py", line 184, in start
self.loop()
File "/home/ansibot/ansibullbot/ansibullbot/triagers/defaulttriager.py", line 295, in loop
self.run()
File …
```
> Disable the www since calculation

- ansibullbot/triagers/ansible.py
- templates/notify.j2
Don't use `pull-request` instead of `issue` and remove superfluous space.
Closes #1059.
> Don't use 'pull-request' instead of 'issue'

- ansibullbot/triagers/ansible.py
- templates/bad_pr.j2
- templates/community_workgroups.j2
- templates/fork.j2
- templates/issue_missing_data.j2
- templates/notify.j2
- templates/thank_submitter.j2
- thank only once:
- `notify` comment can be used multiple times on the same PR
- some other templates (but not all) already thanked the submitter
- only thank PR/issue created after Oct 11 2018 (older might have been thanked already)
cc  @mkrizek / @gundalow
> Rework 'thank submitter'

- shippable.yml
Tests are now run on newer Shippable nodes which have Python 3.7 available by default.
> Remove `pre_ci_boot` from `shippable.yml`.

- ansibullbot/utils/extractors.py
- ansibullbot/utils/moduletools.py
The validate-modules sanity tests no longer allow `authors:` to be defined.
And none of the modules have this specified at this time, so this can go.
> sanity tests no longer allows `authors:`

- .gitmodules
- Vagrantfile
- botmeta_schema_validator/Dockerfile
- docker-compose.yml
- playbooks/roles/ansibullbot.httpd/handlers/main.yml
- playbooks/roles/ansibullbot.httpd/tasks/main.yml
- playbooks/roles/ansibullbot.httpd/templates/ansibot.conf
- playbooks/setup-ansibullbot.yml
- playbooks/update-ansibullbot.yml
Adds docker to the machine and a docker-compose that creates a base infra to include the botmeta validator.
> add docker and botmeta validator infra

- ansibullbot/triagers/ansible.py
- templates/issue_missing_data.j2
- templates/thank_submitter.j2
As this was posted as it's own comment, it was found to be a bit spammy.
The long term fix for this is to have a *single* message when Issues/PRs
are created, see
https://github.com/ansible/ansibullbot/issues/1081#issuecomment-431014207
> [NEEDS TESTING] Remove thank you message

- ansibullbot/utils/shippable_api.py
Fix this exception which occurs with Python 3.7:
File "./triage_ansible.py", line 51, in <module>
main()
File "./triage_ansible.py", line 47, in main
File "ansibullbot/triagers/defaulttriager.py", line 187, in start
self.run()
File "ansibullbot/triagers/ansible.py", line 472, in run
File "ansibullbot/triagers/ansible.py", line 1910, in process
shippable=self.SR
File "ansibullbot/triagers/plugins/needs_revision.py", line 149, in get_needs_revision_facts
ci_date = get_last_shippable_full_run_date(ci_status, shippable)
File "ansibullbot/triagers/plugins/needs_revision.py", line 666, in get_last_shippable_full_run_date
rdata = shippable.get_run_data(to_text(runid), usecache=False)
File …
> Fix TypeError: use bytes (Py3 compat)

- ansibullbot/wrappers/defaultwrapper.py
This should fix https://sentry.io/red-hat-ansibullbot/ansibullbot/issues/828783387/
and will probably fix https://sentry.io/red-hat-ansibullbot/ansibullbot/issues/828783412/
> Treat GitHub's Server Error resp as a Rate Limit

- scripts/generate_issues_by_file.py
Fixes #1142 
Use `to_bytes()` to encode native strings to avoid `UnicodeDecoeError` when encountering a non-ASCII character.
Write files in binary mode for Python 2/3 portability.
> Encode native strings to avoid errors when encountering non-ASCII characters

- ansibullbot/utils/extractors.py
```
Sentry APP [6:25 PM]
unexpected EOF while parsing (<unknown>, line 0)
ANSIBULLBOT-3K via AlertToday at 6:24 PM
Sentry APP [7:03 PM]
unexpected EOF while parsing (<unknown>, line 0)
ANSIBULLBOT-3K via AlertToday at 7:03 PM
Sentry APP [7:41 PM]
unexpected EOF while parsing (<unknown>, line 0)
```
> Only warn on missing metadata

- ansibullbot/triagers/plugins/needs_revision.py
- ansibullbot/utils/moduletools.py
I noticed the following traceback caused by https://github.com/ansible/ansible/pull/56714:
```
IndexError: list index out of range
File "triage_ansible.py", line 45, in <module>
main()
File "triage_ansible.py", line 41, in main
File "ansibullbot/triagers/defaulttriager.py", line 203, in start
self.loop()
File "ansibullbot/triagers/defaulttriager.py", line 314, in loop
self.run()
File "ansibullbot/triagers/ansible.py", line 470, in run
File "ansibullbot/triagers/ansible.py", line 1926, in process
shippable=self.SR
File "ansibullbot/triagers/plugins/needs_revision.py", line 149, in get_needs_revision_facts
ci_date = get_last_shippable_full_run_date(ci_status, shippable)
File "ansibullbot/triagers/plugins/needs_revision.py", line 648, in …
```
> Use shippable states only

- templates/components_banner.j2
Fixes https://github.com/ansible/ansibullbot/issues/1200
Before:
Files identified in the description:
* [lib/ansible/parsing/vault/__init__.py](https://github.com/ansible/ansible/blob/devel/lib/ansible/parsing/vault/__init__.py)
After:
Files identified in the description:
* [`lib/ansible/parsing/vault/__init__.py`](https://github.com/ansible/ansible/blob/devel/lib/ansible/parsing/vault/__init__.py)
> Prevent formatting components in comments

- ansibullbot/triagers/plugins/shipit.py
- tests/unit/triagers/plugins/test_shipit.py
Also fix `owner_pr` for pull requests with changelog fragments.
Fixes https://github.com/ansible/ansibullbot/issues/1205
> Automerge PRs with changelog fragments

- ansibullbot/triagers/plugins/shipit.py
This helps with some of the auditing I run on the backend to look for broken shipit logic.
> Add metadata items to keep track of all shipits even if reset or not authorized

- ansibullbot/wrappers/defaultwrapper.py
https://github.com/ansible/ansible/pull/27757
https://github.com/ansible/ansible/commit/9831ab7e8cbb6d07f68e530c6101becbc95598c9
```
KeyError: u'created_at'
File "triage_ansible.py", line 45, in <module>
main()
File "triage_ansible.py", line 41, in main
File "ansibullbot/triagers/defaulttriager.py", line 203, in start
self.loop()
File "ansibullbot/triagers/defaulttriager.py", line 314, in loop
self.run()
File "ansibullbot/triagers/ansible.py", line 466, in run
self.build_history(iw)
File "ansibullbot/triagers/ansible.py", line 2065, in build_history
iw.history
File "ansibullbot/wrappers/defaultwrapper.py", line 1260, in history
HistoryWrapper(self, cachedir=self.cachedir, usecache=True)
File "ansibullbot/wrappers/historywrapper.py", line 146, in __init__ …
```
> Commit comments do not have created_at

- ansibullbot/wrappers/historywrapper.py
Fixes ...
```
2019-08-29 12:57:22,396 ERROR Uncaught exception
File "/home/ansibot/ansibullbot/triage_ansible.py", line 45, in <module>
main()
File "/home/ansibot/ansibullbot/triage_ansible.py", line 41, in main
AnsibleTriage(args=sys.argv[1:]).start()
File "/home/ansibot/ansibullbot/ansibullbot/triagers/defaulttriager.py", line 177, in start
self.loop()
File "/home/ansibot/ansibullbot/ansibullbot/triagers/defaulttriager.py", line 288, in loop
self.run()
File "/home/ansibot/ansibullbot/ansibullbot/triagers/ansible.py", line 503, in run
File "/home/ansibot/ansibullbot/ansibullbot/triagers/ansible.py", line 1989, in process
self.meta.update(needs_info_timeout_facts(iw, self.meta))
File …
```
> dict events have ids sometimes

- templates/issue_missing_data.j2
Direct people to an issue template which actually includes the headings
> issue_missing_data - correct link

- ansibullbot/triagers/ansible.py
Ensure that the needs_triage label needs to be removed manually which would allow us to comment on issues without worry that they will then be missed in triage.
Fixes #1281
> Never remove needs_triage

- scripts/ansibot_receiver.py
Using `Popen.communicate()` with `PIPE` to capture stdout is problematic when the data is large. From the `subprocess` docs:
> **Note** The data read is buffered in memory, so do not use this method if the data size is large or unlimited.
The log files are rather large and it seems that something is not properly cleaning up the data, resulting in a memory leak.
Loading one log file just to see how big it is.
```
>>> file = '/var/log/ansibullbot.log.1.gz'
>>> p = subprocess.Popen('zcat %s' % file, shell=True, stdout=subprocess.PIPE, stderr=subprocess.PIPE)
>>> so,se = p.communicate()
>>> sys.getsizeof(so)
657176588
```
Monitoring the running process with `pidstat` show `%MEM` and `RSS` steadily increasing.
```
> pidstat -p 15214 -l -r 2
02:32:47 PM   UID       PID  minflt/s  majflt/s …
```
> Use gzip to open log file to avoid memory leak

- ansibullbot/triagers/ansible.py
collection_filemap and collection_file_matches may contain
keys that are no valid keys in mongodb (like `.gitignore`
that contains '.') which results in the flask app
(receiver) crashing and possibly not freeing the memory.
> Possible fix for 1355

- constraints.txt
`cffi` <1.12.2 fails to install on Python > 3.8.0. At a minimum, I need that constraint updated. I went ahead and upgraded all the constraints while I was at it. I'm not sure if I did it properly, though. I wasn't able to figure out how to get the `via -r [file or URL]` comments to not show up. Using the `--no-annotate` option removes all the annotations, which it seems were in the file originally
This is my first time using `pip-compile` so I could use some advice on how to use it properly.
> Upgrade constraints

- playbooks/group_vars/ansibullbot.yml
- playbooks/host_vars/ansibullbot.eng.ansible.com.yml
The bot will triage all repos in the `REPOS` constant. Now that we have added another repo to that list, we need to limit each bot instance to target only the relevant repo.
> Specify repo to triage now that multiple are listed

- .gitmodules
SELinux policy needed a few additional allowances in order to read the git repo.
> Fix git commit on status page

- tests/component/test_supershipit.py
1. automerge is disabled now
2. this test takes too long
3. it is not really an unit test
> Skip supershipit test

- ansibullbot/triagers/plugins/backports.py
While ansible/ansible has specifically "devel", the default branch for collections can be expected to be master or main.
> plugins/backports: consider main and master branches like devel

- ansibullbot/constants.py
- ansibullbot/triagers/ansible.py
- ansibullbot/triagers/defaulttriager.py
- ansibullbot/triagers/plugins/botstatus.py
- ansibullbot/triagers/plugins/ci_rebuild.py
- ansibullbot/triagers/plugins/label_commands.py
- ansibullbot/triagers/plugins/needs_revision.py
- ansibullbot/triagers/plugins/shipit.py
- examples/ansibullbot.cfg
- tests/unit/triagers/plugins/test_shipit.py
Maintainers and committers may be different across different
repositories. As such, we can't hardcode the organization name "ansible"
or the teams so we're pulling it back into a configuration parameter instead.
Since the maintainers are not exclusively ansible core maintainers,
we're also renaming the property to something a bit more generic.
> triagers/ansible: un-hardcode ansible_core_team

- ansibullbot/triagers/defaulttriager.py
Use a dict representation to prevent a traceback with
TypeError: Object of type AnsibleActions is not JSON serializable.
> triagers: fix --dump_actions

- ansibullbot/ci/azp.py
This adds a `timeout` parameter to the `fetch()` calls in `azp.py` that do not have it. Only the change on line 105 is needed to fix the issue, I believe, but adding it other places I don't think will hurt unless the default value of 5 seconds is too low.
Fixes #1585.
> Set timout on fetch in Azure Pipelines to prevent indefinite hanging
